# 01. Car Scrapper

In [1]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
import re
import matplotlib.pyplot as plt

from time import sleep
from random import randint

In [2]:
# The website from where we are going to obtain the data
main_url = "https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=1&cy=E&atype=C&recommended_sorting_based_id=63264e9a-86be-4fce-8e45-42cfcd1def1a&"

In [3]:
# Links for the different categories
small_cars_url = "https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=1&cy=E&body=1&atype=C&recommended_sorting_based_id=63264e9a-86be-4fce-8e45-42cfcd1def1a&"
sedan_cars_url = "https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=1&cy=E&body=6&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&"
familiar_cars_url = "https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=1&cy=E&body=5&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&"
minivan_cars_url = "https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=1&cy=E&body=12&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&"
coupe_cars_url = "https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=1&cy=E&body=3&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&"
cabrio_cars_url = "https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=1&cy=E&body=2&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&"
suv_cars_url = "https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=1&cy=E&body=4&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&"
van_cars_url = "https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=1&cy=E&body=13&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&"
other_cars_url = "https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=1&cy=E&body=7&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&"

In [4]:
#Defining columns for small cars
title = []
version = []
year = []
kms = []
hp = []
gear = []
fuel = []
fuel_cons = []
co2 =[]
prev_owners = []
price = []
location = []

In [5]:
# Analysing urls for the diffenret pages:
# url_pag1 = "https://www.autoscout24.es/lst/?sort=standard&desc=0&ustate=N%2CU&size=20&page=1&cy=E&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&"
# url_pag2 = "https://www.autoscout24.es/lst/?sort=standard&desc=0&ustate=N%2CU&size=20&page=2&cy=E&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&"
# url_pag3 = "https://www.autoscout24.es/lst/?sort=standard&desc=0&ustate=N%2CU&size=20&page=3&cy=E&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&"

# Max page per url = 20 (start: page 1, stop: page 21 -1, step: 1 by 1 as the url changes from page=n to page=n+1 from one page to the following

all_pages = np.arange(1,21,1)

In [6]:
#Scapping small cars

for small_cars_page in all_pages:
    
    small_cars_page = requests.get("https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=" + str(small_cars_page) + "&cy=E&body=1&atype=C&recommended_sorting_based_id=63264e9a-86be-4fce-8e45-42cfcd1def1a&")
    small_cars_soup = BeautifulSoup(small_cars_page.text,"lxml")
    small_cars_ads = small_cars_soup.find_all('div', attrs={"class": "cl-list-element cl-list-element-gap"})
    
    sleep(randint(2,10))
    
    for element in small_cars_ads:
        try:
            Title = element.find('h2', attrs={"class":'cldt-summary-makemodel sc-font-bold sc-ellipsis'}).text
        except:
            Title = ""
        title.append(Title)
        
        try:
            Version = element.find('h2', attrs={"class":"cldt-summary-version sc-ellipsis"}).text
        except:
            Version = ""
        version.append(Version)
        try:
            Year = element.find('li', attrs={'data-type':'first-registration'}).text
        except:
            Year = ""
        year.append(Year)
        try:
            Kms = element.find('li', attrs={"data-type" : "mileage"}).text
        except:
            Kms = ""
        kms.append(Kms)

        try:
            Gear = element.find('li', attrs={"data-type":"transmission-type"}).text
        except:
            Gear = ""
        gear.append(Gear)

        try:
            Fuel = element.find('li', attrs={"class":"summary_item_no_bottom_line"}).text
        except:
            Fuel = ""
        fuel.append(Fuel)

        try:
            Fuel_cons = element.find('li', attrs={"data-type":"combined-consumption"}).text
        except:
            Fuel_cons = ""
        fuel_cons.append(Fuel_cons)

        try:
            Co2 = element.find('li', attrs={"data-type":"co2-emission"}).text
        except:
            Co2 = ""
        co2.append(Co2)

        try:
            Prev_owners = element.find('li', attrs={"data-type" : "previous-owners"}).text
        except:
            Prev_owners = ""
        prev_owners.append(Prev_owners)
        try:
            Price = element.find('span', attrs={"class":"cldt-price sc-font-xl sc-font-bold"}).text
        except:
            Price = ""
        price.append(Price)

        try:
            Hp = element.find('li', text =re.compile(r'CV')).text
        except:
            Hp = ""
        hp.append(Hp)
        
        try:
            Location = element.find('span', attrs={"class":"cldf-summary-seller-contact-zip-city"}).text
        except:
            Location = ""
        location.append(Location)

In [7]:
#Creating the Small_Cars_DataFrame
small_cars_df = pd.DataFrame({"Title":title,
                        "Version":version,
                        "Year": year,
                        "Kms": kms,
                        "Hp": hp,
                        "Fuel_type": fuel,
                        "Gear_type": gear,
                        "Fuel_cons": fuel_cons,
                        "CO2_g/Km": co2,
                        "Previous_owners": prev_owners,
                        "City_ZIP" : location,
                        "Price_EUR": price,
                        "Category" : "Small",
                        "Doors" : "5"})

In [8]:
small_cars_df

,Title,Version,Year,Kms,Hp,Fuel_type,Gear_type,Fuel_cons,CO2_g/Km,Previous_owners,City_ZIP,Price_EUR,Category,Doors
0,SEAT Cordoba,1.9 TDi Sport 90,\n12/2000\n,\n254.000 km\n,\n66 kW (90 CV)\n,\nDiésel\n,\nManual\n,"\n4,9 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,18195 CULLAR VEGA,"\n€ 980,-\nIVA deducible\n",Small,5
1,Rover 25,1.6 Classic,\n01/2001\n,\n171.720 km\n,\n80 kW (109 CV)\n,\nGasolina\n,\nManual\n,\n6 l/100 km (mixto)\nPuede obtenerse informac...,\n- (g/km)\n,\n- (Propietarios)\n,28045 MADRID,"\n€ 1.290,-\n",Small,5
2,SEAT Arosa,1.0 Stylo,\n06/1998\n,\n110.000 km\n,\n37 kW (50 CV)\n,\nGasolina\n,\nManual\n,"\n5,7 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,46940 MANISES,"\n€ 1.450,-\n",Small,5
3,Daewoo Lanos,1.6 16v. SX,\n06/2000\n,\n185.000 km\n,\n78 kW (106 CV)\n,\nGasolina\n,\nManual\n,"\n8,2 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,46940 MANISES,"\n€ 1.500,-\n",Small,5
4,Fiat Panda,1.2 Alessi,\n06/2006\n,\n190.000 km\n,\n44 kW (60 CV)\n,\nGasolina\n,\nManual\n,"\n5,6 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,46940 MANISES,"\n€ 1.950,-\n",Small,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,Audi A3,Sportback 30 TFSI 85kW,\n07/2019\n,\n14.150 km\n,\n85 kW (116 CV)\n,\nGasolina\n,\nManual\n,\n5 l/100 km (mixto)\nPuede obtenerse informac...,\n- (g/km)\n,\n- (Propietarios)\n,08038 BARCELONA,"\n€ 21.900,-\n",Small,5
396,Audi S1,2.0 TFSI quattro,\n03/2015\n,\n98.790 km\n,\n170 kW (231 CV)\n,\nGasolina\n,\nManual\n,\n7 l/100 km (mixto)\nPuede obtenerse informac...,\n- (g/km)\n,\n- (Propietarios)\n,41001 SEVILLA,"\n€ 22.099,-\n",Small,5
397,Peugeot 208,Allure Eléctrico 100kW,\n10/2020\n,\n5.260 km\n,\n100 kW (136 CV)\n,\nEléctrico\n,\nAutomático\n,\n0 l/100 km (mixto)\nPuede obtenerse informac...,\n0 g/km (mixto)\nPuede obtenerse información ...,\n- (Propietarios)\n,28021 MADRID,"\n€ 22.190,-\n",Small,5
398,Volkswagen Golf,2.0TDI Advance DSG7 110kW,\n06/2020\n,\n12.784 km\n,\n110 kW (150 CV)\n,\nDiésel\n,\nAutomático\n,"\n4,3 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,28021 MADRID,"\n€ 22.490,-\n",Small,5
399,Volkswagen Golf,2.0TDI Advance DSG7 110kW,\n06/2020\n,\n21.125 km\n,\n110 kW (150 CV)\n,\nDiésel\n,\nAutomático\n,"\n4,3 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,28021 MADRID,"\n€ 22.490,-\n",Small,5

In [9]:
#Defining columns for sedan cars
title = []
version = []
year = []
kms = []
hp = []
gear = []
fuel = []
fuel_cons = []
co2 =[]
prev_owners = []
price = []
location = []

In [10]:
#Scapping sedan cars

for sedan_cars_page in all_pages:
    
    sedan_cars_page = requests.get("https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=" + str(sedan_cars_page) + "&cy=E&body=6&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&")
    sedan_cars_soup = BeautifulSoup(sedan_cars_page.text,"lxml")
    sedan_cars_ads = sedan_cars_soup.find_all('div', attrs={"class": "cl-list-element cl-list-element-gap"})
    
    sleep(randint(2,10))
    
    for element in sedan_cars_ads:
        try:
            Title = element.find('h2', attrs={"class":'cldt-summary-makemodel sc-font-bold sc-ellipsis'}).text
        except:
            Title = ""
        title.append(Title)
        
        try:
            Version = element.find('h2', attrs={"class":"cldt-summary-version sc-ellipsis"}).text
        except:
            Version = ""
        version.append(Version)
        try:
            Year = element.find('li', attrs={'data-type':'first-registration'}).text
        except:
            Year = ""
        year.append(Year)
        try:
            Kms = element.find('li', attrs={"data-type" : "mileage"}).text
        except:
            Kms = ""
        kms.append(Kms)

        try:
            Gear = element.find('li', attrs={"data-type":"transmission-type"}).text
        except:
            Gear = ""
        gear.append(Gear)

        try:
            Fuel = element.find('li', attrs={"class":"summary_item_no_bottom_line"}).text
        except:
            Fuel = ""
        fuel.append(Fuel)

        try:
            Fuel_cons = element.find('li', attrs={"data-type":"combined-consumption"}).text
        except:
            Fuel_cons = ""
        fuel_cons.append(Fuel_cons)

        try:
            Co2 = element.find('li', attrs={"data-type":"co2-emission"}).text
        except:
            Co2 = ""
        co2.append(Co2)

        try:
            Prev_owners = element.find('li', attrs={"data-type" : "previous-owners"}).text
        except:
            Prev_owners = ""
        prev_owners.append(Prev_owners)
        try:
            Price = element.find('span', attrs={"class":"cldt-price sc-font-xl sc-font-bold"}).text
        except:
            Price = ""
        price.append(Price)

        try:
            Hp = element.find('li', text =re.compile(r'CV')).text
        except:
            Hp = ""
        hp.append(Hp)
        
        try:
            Location = element.find('span', attrs={"class":"cldf-summary-seller-contact-zip-city"}).text
        except:
            Location = ""
        location.append(Location)

In [11]:
#Creating the Sedan_Cars_DataFrame
sedan_cars_df = pd.DataFrame({"Title":title,
                        "Version":version,
                        "Year": year,
                        "Kms": kms,
                        "Hp": hp,
                        "Fuel_type": fuel,
                        "Gear_type": gear,
                        "Fuel_cons": fuel_cons,
                        "CO2_g/Km": co2,
                        "Previous_owners": prev_owners,
                        "City_ZIP" : location,
                        "Price_EUR": price,
                        "Category" : "Sedan",
                        "Doors" : "5"})

In [12]:
sedan_cars_df

,Title,Version,Year,Kms,Hp,Fuel_type,Gear_type,Fuel_cons,CO2_g/Km,Previous_owners,City_ZIP,Price_EUR,Category,Doors
0,Audi A6,2.3,\n11/1995\n,\n291.000 km\n,\n98 kW (133 CV)\n,\nGasolina\n,\nManual\n,\n0 l/100 km (mixto)\nPuede obtenerse informac...,\n- (g/km)\n,\n- (Propietarios)\n,41003 SEVILLA,"\n€ 1.120,-\n",Sedan,5
1,Peugeot 406,1.9 SRSD,\n06/1998\n,\n150.000 km\n,\n68 kW (92 CV)\n,\nDiésel\n,\nManual\n,"\n6,4 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,28021 MADRID,"\n€ 1.200,-\n",Sedan,5
2,Lancia Dedra,1.8 i.e. LE,\n06/1994\n,\n84.000 km\n,\n78 kW (106 CV)\n,\nGasolina\n,\nManual\n,\n0 l/100 km (mixto)\nPuede obtenerse informac...,\n- (g/km)\n,\n- (Propietarios)\n,26500 CALAHORRA,"\n€ 1.499,-\n",Sedan,5
3,Fiat Marea,1.9 TD 100 SX,\n10/1999\n,\n158.994 km\n,\n74 kW (101 CV)\n,\nDiésel\n,\nManual\n,"\n6,2 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,48970 BASAURI,"\n€ 1.500,-\n",Sedan,5
4,Mercedes-Benz C 250,Turbo Diesel,\n01/1998\n,\n260.000 km\n,\n110 kW (150 CV)\n,\nDiésel\n,\nManual\n,"\n7,3 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,37300 PEÑARANDA DE BRACAMONTE,"\n€ 1.799,-\n",Sedan,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,Mercedes-Benz 220,C d AMG Line,\n07/2018\n,\n31.914 km\n,\n125 kW (170 CV)\n,\nDiésel\n,\nAutomático\n,\n- (l/100 km)\n,\n- (g/km)\n,\n- (Propietarios)\n,41001 SEVILLA,"\n€ 27.026,-\n",Sedan,5
396,Mercedes-Benz 220,C d AMG Line,\n07/2018\n,\n31.914 km\n,\n125 kW (170 CV)\n,\nDiésel\n,\nAutomático\n,\n- (l/100 km)\n,\n- (g/km)\n,\n- (Propietarios)\n,28050 MADRID,"\n€ 27.026,-\n",Sedan,5
397,Mercedes-Benz 220,C d AMG Line,\n07/2018\n,\n31.914 km\n,\n125 kW (170 CV)\n,\nDiésel\n,\nAutomático\n,\n- (l/100 km)\n,\n- (g/km)\n,\n- (Propietarios)\n,8903 SANT ADRIÀ DE BESÒS,"\n€ 27.026,-\n",Sedan,5
398,Audi A3,SPORT BACK 2.0 35 TDI BLACK LINE SPORTBACK 5P,\n02/2020\n,\n13.000 km\n,\n1 kW (1 CV)\n,\nDiésel\n,\nManual\n,\n- (l/100 km)\n,\n- (g/km)\n,\n- (Propietarios)\n,08030 BARCELONA,"\n€ 27.200,-\n",Sedan,5
399,Audi A3,1.5 35 TFSI S LINE SPORTBACK 150 5P,\n02/2020\n,\n23.394 km\n,\n110 kW (150 CV)\n,\nGasolina\n,\nManual\n,\n- (l/100 km)\n,\n- (g/km)\n,\n- (Propietarios)\n,30313 CARTAGENA,"\n€ 27.200,-\n",Sedan,5

In [13]:
#Defining columns for familiar cars
title = []
version = []
year = []
kms = []
hp = []
gear = []
fuel = []
fuel_cons = []
co2 =[]
prev_owners = []
price = []
location = []

In [14]:
#Scapping familiar cars

for familiar_cars_page in all_pages:
    
    familiar_cars_page = requests.get("https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=" + str(familiar_cars_page) + "&cy=E&body=5&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&")
    familiar_cars_soup = BeautifulSoup(familiar_cars_page.text,"lxml")
    familiar_cars_ads = familiar_cars_soup.find_all('div', attrs={"class": "cl-list-element cl-list-element-gap"})
    
    sleep(randint(2,10))
    
    for element in familiar_cars_ads:
        try:
            Title = element.find('h2', attrs={"class":'cldt-summary-makemodel sc-font-bold sc-ellipsis'}).text
        except:
            Title = ""
        title.append(Title)
        
        try:
            Version = element.find('h2', attrs={"class":"cldt-summary-version sc-ellipsis"}).text
        except:
            Version = ""
        version.append(Version)
        try:
            Year = element.find('li', attrs={'data-type':'first-registration'}).text
        except:
            Year = ""
        year.append(Year)
        try:
            Kms = element.find('li', attrs={"data-type" : "mileage"}).text
        except:
            Kms = ""
        kms.append(Kms)

        try:
            Gear = element.find('li', attrs={"data-type":"transmission-type"}).text
        except:
            Gear = ""
        gear.append(Gear)

        try:
            Fuel = element.find('li', attrs={"class":"summary_item_no_bottom_line"}).text
        except:
            Fuel = ""
        fuel.append(Fuel)

        try:
            Fuel_cons = element.find('li', attrs={"data-type":"combined-consumption"}).text
        except:
            Fuel_cons = ""
        fuel_cons.append(Fuel_cons)

        try:
            Co2 = element.find('li', attrs={"data-type":"co2-emission"}).text
        except:
            Co2 = ""
        co2.append(Co2)

        try:
            Prev_owners = element.find('li', attrs={"data-type" : "previous-owners"}).text
        except:
            Prev_owners = ""
        prev_owners.append(Prev_owners)
        try:
            Price = element.find('span', attrs={"class":"cldt-price sc-font-xl sc-font-bold"}).text
        except:
            Price = ""
        price.append(Price)

        try:
            Hp = element.find('li', text =re.compile(r'CV')).text
        except:
            Hp = ""
        hp.append(Hp)
        
        try:
            Location = element.find('span', attrs={"class":"cldf-summary-seller-contact-zip-city"}).text
        except:
            Location = ""
        location.append(Location)

In [15]:
#Creating the Familiar_Cars_DataFrame
familiar_cars_df = pd.DataFrame({"Title":title,
                        "Version":version,
                        "Year": year,
                        "Kms": kms,
                        "Hp": hp,
                        "Fuel_type": fuel,
                        "Gear_type": gear,
                        "Fuel_cons": fuel_cons,
                        "CO2_g/Km": co2,
                        "Previous_owners": prev_owners,
                        "City_ZIP" : location,
                        "Price_EUR": price,
                        "Category" : "Wagon",
                        "Doors" : "5"})

In [16]:
familiar_cars_df

,Title,Version,Year,Kms,Hp,Fuel_type,Gear_type,Fuel_cons,CO2_g/Km,Previous_owners,City_ZIP,Price_EUR,Category,Doors
0,Peugeot 307,SW Pack + 1.6 HDI 90CV --- EMBRAGUE ROTO --,\n11/2006\n,\n201.000 km\n,\n66 kW (90 CV)\n,\nDiésel\n,\nManual\n,"\n5,1 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,08020 BARCELONA,"\n€ 1.890,-\n",Wagon,5
1,Volvo 850,Estate 2.0 10v,\n06/1995\n,\n128.000 km\n,\n93 kW (126 CV)\n,\nGasolina\n,\nManual\n,\n0 l/100 km (mixto)\nPuede obtenerse informac...,\n- (g/km)\n,\n- (Propietarios)\n,03580 ALFAZ DEL PI,"\n€ 2.490,-\n",Wagon,5
2,Opel Astra,SW 1.7CDTi Enjoy 6vel.,\n03/2007\n,\n197.300 km\n,\n73 kW (99 CV)\n,\nDiésel\n,\nManual\n,\n5 l/100 km (mixto)\nPuede obtenerse informac...,\n- (g/km)\n,\n- (Propietarios)\n,48960 GALDAKAO,"\n€ 2.490,-\n",Wagon,5
3,Citroen Evasion,2.0 LANDSCAPE,\n10/1998\n,\n156.567 km\n,\n90 kW (122 CV)\n,\nGasolina\n,\nManual\n,"\n10,6 l/100 km (mixto)\nPuede obtenerse infor...",\n- (g/km)\n,\n- (Propietarios)\n,06200 ALMENDRALEJO,"\n€ 2.500,-\n",Wagon,5
4,Volkswagen Passat,Variant 2.0TDI Highline,\n02/2006\n,\n350.000 km\n,\n103 kW (140 CV)\n,\nDiésel\n,\nManual\n,"\n5,9 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,28903 GETAFE,"\n€ 2.800,-\n",Wagon,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,Peugeot 508,SW 2.0 BlueHDi S&S GT Line EAT8 160,\n05/2019\n,\n75.507 km\n,\n120 kW (163 CV)\n,\nDiésel\n,\nAutomático\n,"\n4,6 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,28944 FUENLABRADA,"\n€ 25.990,-\n",Wagon,5
396,BMW 325,d Touring,\n10/2017\n,\n108.657 km\n,\n165 kW (224 CV)\n,\nDiésel\n,\nManual\n,"\n4,9 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,08172 SANT CUGAT DEL VALLÈS,"\n€ 25.990,-\n",Wagon,5
397,Renault Talisman,S.T. dCi Blue Zen EDC 118kW,\n09/2020\n,\n17.505 km\n,\n118 kW (160 CV)\n,\nDiésel\n,\nAutomático\n,"\n4,9 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,39011 SANTANDER,"\n€ 25.990,-\n",Wagon,5
398,Ford Focus,Sportbreak 2.0Ecoblue ST Line Aut,\n01/2020\n,\n10.000 km\n,\n110 kW (150 CV)\n,\nDiésel\n,\nAutomático\n,"\n4,6 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,8908 Hospitalet de Llobregat,"\n€ 26.900,-\n",Wagon,5
399,Volvo V90,D4 Momentum Aut. 190,\n03/2019\n,\n24.540 km\n,\n140 kW (190 CV)\n,\nDiésel\n,\nAutomático\n,"\n4,9 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,28021 MADRID,"\n€ 27.190,-\n",Wagon,5

In [17]:
#Defining columns for minivan cars
title = []
version = []
year = []
kms = []
hp = []
gear = []
fuel = []
fuel_cons = []
co2 =[]
prev_owners = []
price = []
location = []

In [18]:
#Scapping minivans cars

for minivan_cars_page in all_pages:
    
    minivan_cars_page = requests.get("https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=" + str(minivan_cars_page) + "&cy=E&body=12&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&")
    minivan_cars_soup = BeautifulSoup(minivan_cars_page.text,"lxml")
    minivan_cars_ads = minivan_cars_soup.find_all('div', attrs={"class": "cl-list-element cl-list-element-gap"})
    
    sleep(randint(2,10))
    
    for element in minivan_cars_ads:
        
        try:
            Title = element.find('h2', attrs={"class":'cldt-summary-makemodel sc-font-bold sc-ellipsis'}).text
        except:
            Title = ""
        title.append(Title)
        
        try:
            Version = element.find('h2', attrs={"class":"cldt-summary-version sc-ellipsis"}).text
        except:
            Version = ""
        version.append(Version)
        try:
            Year = element.find('li', attrs={'data-type':'first-registration'}).text
        except:
            Year = ""
        year.append(Year)
        try:
            Kms = element.find('li', attrs={"data-type" : "mileage"}).text
        except:
            Kms = ""
        kms.append(Kms)

        try:
            Gear = element.find('li', attrs={"data-type":"transmission-type"}).text
        except:
            Gear = ""
        gear.append(Gear)

        try:
            Fuel = element.find('li', attrs={"class":"summary_item_no_bottom_line"}).text
        except:
            Fuel = ""
        fuel.append(Fuel)

        try:
            Fuel_cons = element.find('li', attrs={"data-type":"combined-consumption"}).text
        except:
            Fuel_cons = ""
        fuel_cons.append(Fuel_cons)

        try:
            Co2 = element.find('li', attrs={"data-type":"co2-emission"}).text
        except:
            Co2 = ""
        co2.append(Co2)

        try:
            Prev_owners = element.find('li', attrs={"data-type" : "previous-owners"}).text
        except:
            Prev_owners = ""
        prev_owners.append(Prev_owners)
        try:
            Price = element.find('span', attrs={"class":"cldt-price sc-font-xl sc-font-bold"}).text
        except:
            Price = ""
        price.append(Price)

        try:
            Hp = element.find('li', text =re.compile(r'CV')).text
        except:
            Hp = ""
        hp.append(Hp)
        
        try:
            Location = element.find('span', attrs={"class":"cldf-summary-seller-contact-zip-city"}).text
        except:
            Location = ""
        location.append(Location)

In [19]:
#Creating the Minivan_Cars_DataFrame
minivan_cars_df = pd.DataFrame({"Title":title,
                        "Version":version,
                        "Year": year,
                        "Kms": kms,
                        "Hp": hp,
                        "Fuel_type": fuel,
                        "Gear_type": gear,
                        "Fuel_cons": fuel_cons,
                        "CO2_g/Km": co2,
                        "Previous_owners": prev_owners,
                        "City_ZIP" : location,
                        "Price_EUR": price,
                        "Category" : "Minivan",
                        "Doors" : "5"})

In [20]:
minivan_cars_df

,Title,Version,Year,Kms,Hp,Fuel_type,Gear_type,Fuel_cons,CO2_g/Km,Previous_owners,City_ZIP,Price_EUR,Category,Doors
0,Opel Zafira,2.2Dti 16v Elegance,\n05/2002\n,\n158.000 km\n,\n92 kW (125 CV)\n,\nDiésel\n,\nManual\n,"\n6,9 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,08020 BARCELONA,"\n€ 2.390,-\n",Minivan,5
1,Renault Espace,2.2 dCi Expression,\n07/2004\n,\n267.000 km\n,\n110 kW (150 CV)\n,\nDiésel\n,\nManual\n,"\n7,7 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,29004 MALAGA,"\n€ 3.250,-\n",Minivan,5
2,SEAT Altea XL,XL 1.9TDI Reference,\n01/2010\n,\n233.209 km\n,\n77 kW (105 CV)\n,\nDiésel\n,\nManual\n,"\n5,4 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,46930 QUART DE POBLET,"\n€ 3.400,-\n",Minivan,5
3,Ford C-Max,Focus Newport 1.8 Flexifuel 125cv,\n06/2007\n,\n80.700 km\n,\n92 kW (125 CV)\n,\nDiésel\n,\nAutomático\n,"\n7,1 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,29750 Algarrobo-Costa,"\n€ 3.500,-\n",Minivan,5
4,Mercedes-Benz B 200,200CDI Autotronic,\n07/2007\n,\n280.000 km\n,\n102 kW (139 CV)\n,\nDiésel\n,\nAutomático\n,"\n5,6 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,48940 LEIOA,"\n€ 3.690,-\n",Minivan,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,Citroen Xsara,Picasso 1.6i 95,\n09/2001\n,\n131.098 km\n,\n70 kW (95 CV)\n,\nGasolina\n,\nManual\n,"\n7,5 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,28935 MOSTOLES,"\n€ 1.900,-\n",Minivan,5
396,Citroen Xsara,Picasso 1.6i 95,\n09/2001\n,\n131.098 km\n,\n70 kW (95 CV)\n,\nGasolina\n,\nManual\n,"\n7,5 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,28906 GETAFE,"\n€ 1.900,-\n",Minivan,5
397,Citroen Xsara,Picasso 1.6i 95,\n09/2001\n,\n131.098 km\n,\n70 kW (95 CV)\n,\nGasolina\n,\nManual\n,"\n7,5 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,28232 LAS ROZAS,"\n€ 1.900,-\n",Minivan,5
398,Citroen Xsara,Picasso 1.6i 95,\n09/2001\n,\n131.098 km\n,\n70 kW (95 CV)\n,\nGasolina\n,\nManual\n,"\n7,5 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,03006 Alicante,"\n€ 1.900,-\n",Minivan,5
399,Citroen Xsara,Picasso 1.6i 95,\n09/2001\n,\n131.098 km\n,\n70 kW (95 CV)\n,\nGasolina\n,\nManual\n,"\n7,5 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,30007 Murcia,"\n€ 1.900,-\n",Minivan,5

In [21]:
#Defining columns for coupe cars
title = []
version = []
year = []
kms = []
hp = []
gear = []
fuel = []
fuel_cons = []
co2 =[]
prev_owners = []
price = []
location = []

In [22]:
#Scapping coupe cars

for coupe_cars_page in all_pages:
    
    coupe_cars_page = requests.get("https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=" + str(coupe_cars_page) + "&cy=E&body=3&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&")
    coupe_cars_soup = BeautifulSoup(coupe_cars_page.text,"lxml")
    coupe_cars_ads = coupe_cars_soup.find_all('div', attrs={"class": "cl-list-element cl-list-element-gap"})
    
    sleep(randint(2,10))
    
    for element in coupe_cars_ads:
        try:
            Title = element.find('h2', attrs={"class":'cldt-summary-makemodel sc-font-bold sc-ellipsis'}).text
        except:
            Title = ""
        title.append(Title)
        
        try:
            Version = element.find('h2', attrs={"class":"cldt-summary-version sc-ellipsis"}).text
        except:
            Version = ""
        version.append(Version)
        try:
            Year = element.find('li', attrs={'data-type':'first-registration'}).text
        except:
            Year = ""
        year.append(Year)
        try:
            Kms = element.find('li', attrs={"data-type" : "mileage"}).text
        except:
            Kms = ""
        kms.append(Kms)

        try:
            Gear = element.find('li', attrs={"data-type":"transmission-type"}).text
        except:
            Gear = ""
        gear.append(Gear)

        try:
            Fuel = element.find('li', attrs={"class":"summary_item_no_bottom_line"}).text
        except:
            Fuel = ""
        fuel.append(Fuel)

        try:
            Fuel_cons = element.find('li', attrs={"data-type":"combined-consumption"}).text
        except:
            Fuel_cons = ""
        fuel_cons.append(Fuel_cons)

        try:
            Co2 = element.find('li', attrs={"data-type":"co2-emission"}).text
        except:
            Co2 = ""
        co2.append(Co2)

        try:
            Prev_owners = element.find('li', attrs={"data-type" : "previous-owners"}).text
        except:
            Prev_owners = ""
        prev_owners.append(Prev_owners)
        try:
            Price = element.find('span', attrs={"class":"cldt-price sc-font-xl sc-font-bold"}).text
        except:
            Price = ""
        price.append(Price)

        try:
            Hp = element.find('li', text =re.compile(r'CV')).text
        except:
            Hp = ""
        hp.append(Hp)
        
        try:
            Location = element.find('span', attrs={"class":"cldf-summary-seller-contact-zip-city"}).text
        except:
            Location = ""
        location.append(Location)

In [23]:
#Creating the Coupe_Cars_DataFrame
coupe_cars_df = pd.DataFrame({"Title":title,
                        "Version":version,
                        "Year": year,
                        "Kms": kms,
                        "Hp": hp,
                        "Fuel_type": fuel,
                        "Gear_type": gear,
                        "Fuel_cons": fuel_cons,
                        "CO2_g/Km": co2,
                        "Previous_owners": prev_owners,
                        "City_ZIP" : location,
                        "Price_EUR": price,
                        "Category" : "Coupe",
                        "Doors" : "3"})

In [24]:
coupe_cars_df

,Title,Version,Year,Kms,Hp,Fuel_type,Gear_type,Fuel_cons,CO2_g/Km,Previous_owners,City_ZIP,Price_EUR,Category,Doors
0,Mercedes-Benz C 200,Sportcoupé K,\n09/2003\n,\n267.000 km\n,\n120 kW (163 CV)\n,\nGasolina\n,\nAutomático\n,"\n9,7 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,8304 MATARO,"\n€ 2.950,-\n",Coupe,3
1,Mercedes-Benz C 200,Sportcoupé K,\n01/2002\n,\n203.000 km\n,\n120 kW (163 CV)\n,\nGasolina\n,\nManual\n,"\n9,7 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,29004 MALAGA,"\n€ 2.950,-\n",Coupe,3
2,Mercedes-Benz C 200,C 200 Sportcoupé K,\n12/2002\n,\n182.000 km\n,\n120 kW (163 CV)\n,\nGasolina\n,\nManual\n,"\n9,7 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,46940 MANISES,"\n€ 4.500,-\n",Coupe,3
3,BMW 320,Ci,\n06/2002\n,\n186.600 km\n,\n125 kW (170 CV)\n,\nGasolina\n,\nManual\n,"\n8,9 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,46980 PATERNA,"\n€ 4.600,-\n",Coupe,3
4,Mercedes-Benz CLK 200,K,\n03/2004\n,\n291.200 km\n,\n120 kW (163 CV)\n,\nGasolina\n,\nManual\n,"\n12,2 l/100 km (mixto)\nPuede obtenerse infor...",\n- (g/km)\n,\n- (Propietarios)\n,46980 PATERNA,"\n€ 4.700,-\n",Coupe,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,Mercedes-Benz SL 500,,\n10/1995\n,\n103.000 km\n,\n235 kW (320 CV)\n,\nGasolina\n,\nAutomático\n,\n0 l/100 km (mixto)\nPuede obtenerse informac...,\n- (g/km)\n,\n- (Propietarios)\n,08013 BARCELONA,"\n€ 19.900,-\n",Coupe,3
396,Fiat 124 Spider,1.4 Multiair Lusso,\n04/2017\n,\n54.774 km\n,\n103 kW (140 CV)\n,\nGasolina\n,\nManual\n,"\n6,4 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,46190 RIBARROJA DEL TURIA,"\n€ 19.900,-\n",Coupe,3
397,Audi A5,COUPE 2.0 TDI CLEAN D 190 CV MULTITRONIC S LIN...,\n01/2016\n,\n67.877 km\n,\n140 kW (190 CV)\n,\nDiésel\n,\nAutomático\n,\n- (l/100 km)\n,\n- (g/km)\n,\n- (Propietarios)\n,08226 TERRASSA,"\n€ 19.900,-\n",Coupe,3
398,Mazda MX-5,RF 2.0 Luxury Sport,\n03/2017\n,\n56.354 km\n,\n118 kW (160 CV)\n,\nGasolina\n,\nManual\n,"\n6,9 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,28045 MADRID,"\n€ 20.990,-\n",Coupe,3
399,Audi A7,Sportback 3.0TDI quattro S-Tronic 204,\n05/2011\n,\n130.000 km\n,\n150 kW (204 CV)\n,\nDiésel\n,\nAutomático\n,"\n5,8 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,29601 MARBELLA,"\n€ 20.990,-\n",Coupe,3

In [25]:
#Defining columns for cabrio cars
title = []
version = []
year = []
kms = []
hp = []
gear = []
fuel = []
fuel_cons = []
co2 =[]
prev_owners = []
price = []
location = []

In [26]:
#Scapping cabrio cars

for cabrio_cars_page in all_pages:
    
    cabrio_cars_page = requests.get("https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=" + str(cabrio_cars_page) + "&cy=E&body=2&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&")
    cabrio_cars_soup = BeautifulSoup(cabrio_cars_page.text,"lxml")
    cabrio_cars_ads = cabrio_cars_soup.find_all('div', attrs={"class": "cl-list-element cl-list-element-gap"})
    
    sleep(randint(2,10))
    
    for element in cabrio_cars_ads:
        try:
            Title = element.find('h2', attrs={"class":'cldt-summary-makemodel sc-font-bold sc-ellipsis'}).text
        except:
            Title = ""
        title.append(Title)
        
        try:
            Version = element.find('h2', attrs={"class":"cldt-summary-version sc-ellipsis"}).text
        except:
            Version = ""
        version.append(Version)
        try:
            Year = element.find('li', attrs={'data-type':'first-registration'}).text
        except:
            Year = ""
        year.append(Year)
        try:
            Kms = element.find('li', attrs={"data-type" : "mileage"}).text
        except:
            Kms = ""
        kms.append(Kms)

        try:
            Gear = element.find('li', attrs={"data-type":"transmission-type"}).text
        except:
            Gear = ""
        gear.append(Gear)

        try:
            Fuel = element.find('li', attrs={"class":"summary_item_no_bottom_line"}).text
        except:
            Fuel = ""
        fuel.append(Fuel)

        try:
            Fuel_cons = element.find('li', attrs={"data-type":"combined-consumption"}).text
        except:
            Fuel_cons = ""
        fuel_cons.append(Fuel_cons)

        try:
            Co2 = element.find('li', attrs={"data-type":"co2-emission"}).text
        except:
            Co2 = ""
        co2.append(Co2)

        try:
            Prev_owners = element.find('li', attrs={"data-type" : "previous-owners"}).text
        except:
            Prev_owners = ""
        prev_owners.append(Prev_owners)
        try:
            Price = element.find('span', attrs={"class":"cldt-price sc-font-xl sc-font-bold"}).text
        except:
            Price = ""
        price.append(Price)

        try:
            Hp = element.find('li', text =re.compile(r'CV')).text
        except:
            Hp = ""
        hp.append(Hp)
        
        try:
            Location = element.find('span', attrs={"class":"cldf-summary-seller-contact-zip-city"}).text
        except:
            Location = ""
        location.append(Location)

In [27]:
#Creating the Cabrio_Cars_DataFrame
cabrio_cars_df = pd.DataFrame({"Title":title,
                        "Version":version,
                        "Year": year,
                        "Kms": kms,
                        "Hp": hp,
                        "Fuel_type": fuel,
                        "Gear_type": gear,
                        "Fuel_cons": fuel_cons,
                        "CO2_g/Km": co2,
                        "Previous_owners": prev_owners,
                        "City_ZIP" : location,
                        "Price_EUR": price,
                        "Category" : "Convertible",
                        "Doors" : "3"})

In [28]:
cabrio_cars_df

,Title,Version,Year,Kms,Hp,Fuel_type,Gear_type,Fuel_cons,CO2_g/Km,Previous_owners,City_ZIP,Price_EUR,Category,Doors
0,Mitsubishi Colt,CZC 1.5 16v Instyle,\n06/2006\n,\n83.000 km\n,\n80 kW (109 CV)\n,\nGasolina\n,\nManual\n,"\n6,6 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,46930 QUART DE POBLET,"\n€ 2.200,-\n",Convertible,3
1,Opel Astra,Twin Top 1.6 Enjoy,\n10/2007\n,\n110.000 km\n,\n77 kW (105 CV)\n,\nGasolina\n,\nManual\n,\n7 l/100 km (mixto)\nPuede obtenerse informac...,\n- (g/km)\n,\n- (Propietarios)\n,23700 LINARES,"\n€ 3.999,-\n",Convertible,3
2,Renault Megane,C.C. 1.9DCI Luxe Dynamique 130,\n07/2005\n,\n200.000 km\n,\n96 kW (131 CV)\n,\nDiésel\n,\nManual\n,"\n5,8 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,24009 LEON,"\n€ 5.000,-\n",Convertible,3
3,Volkswagen Beetle,Cabrio 1.9TDI,\n04/2004\n,\n177.300 km\n,\n73 kW (99 CV)\n,\nDiésel\n,\nManual\n,"\n5,5 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,48960 GALDAKAO,"\n€ 5.490,-\n",Convertible,3
4,Saab 9-3,Cabrio 1.9TiD Vector 20 Aniversario,\n04/2006\n,\n222.960 km\n,\n110 kW (150 CV)\n,\nDiésel\n,\nManual\n,"\n6,3 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,46470 MASSANASSA,"\n€ 5.500,-\n",Convertible,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,Peugeot 307,CC 2.0HDI Sport 136,\n02/2007\n,\n100.000 km\n,\n100 kW (136 CV)\n,\nDiésel\n,\nManual\n,\n6 l/100 km (mixto)\nPuede obtenerse informac...,\n159 g/km (mixto)\nPuede obtenerse informació...,\n- (Propietarios)\n,,"\n€ 5.500,-\n",Convertible,3
396,BMW Z3,1.9i Roadster,\n03/1999\n,\n188.000 km\n,\n103 kW (140 CV)\n,\nGasolina\n,\nManual\n,\n8 l/100 km (mixto)\nPuede obtenerse informac...,\n- (g/km)\n,\n- (Propietarios)\n,,"\n€ 5.500,-\n",Convertible,3
397,Mercedes-Benz E 220,Sportline,\n09/1996\n,\n371.000 km\n,\n110 kW (150 CV)\n,\nGasolina\n,\nAutomático\n,\n- (l/100 km)\n,\n- (g/km)\n,\n- (Propietarios)\n,,"\n€ 5.500,-\n",Convertible,3
398,Mercedes-Benz SLK 230,K,\n04/1997\n,\n132.000 km\n,\n142 kW (193 CV)\n,\nGasolina\n,\nManual\n,"\n8,1 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,,"\n€ 5.500,-\nIVA deducible\n",Convertible,3
399,Mercedes-Benz CLK 230,Cabrio K Avantgarde,\n05/1999\n,\n148.280 km\n,\n142 kW (193 CV)\n,\nGasolina\n,\nManual\n,"\n10,1 l/100 km (mixto)\nPuede obtenerse infor...",\n- (g/km)\n,\n- (Propietarios)\n,36314 VIGO,"\n€ 5.500,-\n",Convertible,3

In [29]:
#Defining columns for suv cars
title = []
version = []
year = []
kms = []
hp = []
gear = []
fuel = []
fuel_cons = []
co2 =[]
prev_owners = []
price = []
location = []

In [30]:
#Scapping suv cars

for suv_cars_page in all_pages:
    
    suv_cars_page = requests.get("https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=" + str(suv_cars_page) + "&cy=E&body=4&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&")
    suv_cars_soup = BeautifulSoup(suv_cars_page.text,"lxml")
    suv_cars_ads = suv_cars_soup.find_all('div', attrs={"class": "cl-list-element cl-list-element-gap"})
    
    sleep(randint(2,10))
    
    for element in suv_cars_ads:
        try:
            Title = element.find('h2', attrs={"class":'cldt-summary-makemodel sc-font-bold sc-ellipsis'}).text
        except:
            Title = ""
        title.append(Title)
        
        try:
            Version = element.find('h2', attrs={"class":"cldt-summary-version sc-ellipsis"}).text
        except:
            Version = ""
        version.append(Version)
        try:
            Year = element.find('li', attrs={'data-type':'first-registration'}).text
        except:
            Year = ""
        year.append(Year)
        try:
            Kms = element.find('li', attrs={"data-type" : "mileage"}).text
        except:
            Kms = ""
        kms.append(Kms)

        try:
            Gear = element.find('li', attrs={"data-type":"transmission-type"}).text
        except:
            Gear = ""
        gear.append(Gear)

        try:
            Fuel = element.find('li', attrs={"class":"summary_item_no_bottom_line"}).text
        except:
            Fuel = ""
        fuel.append(Fuel)

        try:
            Fuel_cons = element.find('li', attrs={"data-type":"combined-consumption"}).text
        except:
            Fuel_cons = ""
        fuel_cons.append(Fuel_cons)

        try:
            Co2 = element.find('li', attrs={"data-type":"co2-emission"}).text
        except:
            Co2 = ""
        co2.append(Co2)

        try:
            Prev_owners = element.find('li', attrs={"data-type" : "previous-owners"}).text
        except:
            Prev_owners = ""
        prev_owners.append(Prev_owners)
        try:
            Price = element.find('span', attrs={"class":"cldt-price sc-font-xl sc-font-bold"}).text
        except:
            Price = ""
        price.append(Price)

        try:
            Hp = element.find('li', text =re.compile(r'CV')).text
        except:
            Hp = ""
        hp.append(Hp)
        
        try:
            Location = element.find('span', attrs={"class":"cldf-summary-seller-contact-zip-city"}).text
        except:
            Location = ""
        location.append(Location)

In [31]:
#Creating the Suv_Cars_DataFrame
suv_cars_df = pd.DataFrame({"Title":title,
                        "Version":version,
                        "Year": year,
                        "Kms": kms,
                        "Hp": hp,
                        "Fuel_type": fuel,
                        "Gear_type": gear,
                        "Fuel_cons": fuel_cons,
                        "CO2_g/Km": co2,
                        "Previous_owners": prev_owners,
                        "City_ZIP" : location,
                        "Price_EUR": price,
                        "Category" : "Suv",
                        "Doors" : "5"})

In [32]:
suv_cars_df

,Title,Version,Year,Kms,Hp,Fuel_type,Gear_type,Fuel_cons,CO2_g/Km,Previous_owners,City_ZIP,Price_EUR,Category,Doors
0,Audi Allroad,2.7T quattro Tiptronic,\n07/2001\n,\n277.000 km\n,\n184 kW (250 CV)\n,\nGasolina\n,\nAutomático\n,\n12 l/100 km (mixto)\nPuede obtenerse informa...,\n- (g/km)\n,\n- (Propietarios)\n,04230 VIATOR,"\n€ 2.650,-\n",Suv,5
1,Nissan X-Trail,2.5 Elegance,\n03/2004\n,\n108.900 km\n,\n121 kW (165 CV)\n,\nGasolina\n,\nManual\n,"\n9,6 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,18195 CULLAR VEGA,"\n€ 3.450,-\nIVA deducible\n",Suv,5
2,SsangYong REXTON,270 Full GRAN OCASION NACIONAL,\n12/2004\n,\n299.000 km\n,\n121 kW (165 CV)\n,\nDiésel\n,\nAutomático\n,"\n8,6 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,23700 LINARES,"\n€ 3.499,-\n",Suv,5
3,Audi Allroad,2.5 TDI quattro Tiptronic,\n12/2003\n,\n389.000 km\n,\n132 kW (179 CV)\n,\nDiésel\n,\nAutomático\n,"\n9,6 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,28891 VELILLA DE SAN ANTONIO,"\n€ 3.900,-\n",Suv,5
4,Kia Sorento,2.5CRDI EX2 TOD,\n10/2005\n,\n240.000 km\n,\n103 kW (140 CV)\n,\nDiésel\n,\nManual\n,"\n8,5 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,46910 BENETUSER,"\n€ 3.998,-\n",Suv,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,Peugeot 3008,2.0BLUEHDI 133KW (180CV) GT AUTO S&S,\n04/2017\n,\n119.181 km\n,\n133 kW (181 CV)\n,\nDiésel\n,\nAutomático\n,"\n4,9 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,28021 MADRID,"\n€ 20.190,-\n",Suv,5
396,Land Rover Range Rover Evoque,2.0eD4 SE Dynamic 2WD 150,\n11/2016\n,\n59.000 km\n,\n110 kW (150 CV)\n,\nDiésel\n,\nManual\n,"\n4,3 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,28936 MOSTOLES,"\n€ 20.289,-\n",Suv,5
397,Volkswagen Passat Alltrack,2.0TDI 4Motion DSG 140kW,\n06/2017\n,\n112.439 km\n,\n140 kW (190 CV)\n,\nDiésel\n,\nAutomático\n,"\n4,8 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,8903 SANT ADRIÀ DE BESÒS,"\n€ 20.299,-\n",Suv,5
398,Audi Q3,2.0TDI Sport edition 110kW,\n06/2017\n,\n121.693 km\n,\n110 kW (150 CV)\n,\nDiésel\n,\nManual\n,"\n4,6 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,30100 Murcia,"\n€ 20.300,-\n",Suv,5
399,Audi Q3,1.4 TFSI CoD Sport edition S tronic,\n12/2017\n,\n49.263 km\n,\n110 kW (150 CV)\n,\nGasolina\n,\nAutomático\n,"\n6,2 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,28021 MADRID,"\n€ 20.390,-\n",Suv,5

In [33]:
#Defining columns for Van cars
title = []
version = []
year = []
kms = []
hp = []
gear = []
fuel = []
fuel_cons = []
co2 =[]
prev_owners = []
price = []
location = []

In [34]:
#Scapping Van cars

for van_cars_page in all_pages:
    
    van_cars_page = requests.get("https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=" + str(van_cars_page) + "&cy=E&body=13&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&")
    van_cars_soup = BeautifulSoup(van_cars_page.text,"lxml")
    van_cars_ads = van_cars_soup.find_all('div', attrs={"class": "cl-list-element cl-list-element-gap"})
    
    sleep(randint(2,10))
    
    for element in van_cars_ads:
        try:
            Title = element.find('h2', attrs={"class":'cldt-summary-makemodel sc-font-bold sc-ellipsis'}).text
        except:
            Title = ""
        title.append(Title)
        
        try:
            Version = element.find('h2', attrs={"class":"cldt-summary-version sc-ellipsis"}).text
        except:
            Version = ""
        version.append(Version)
        try:
            Year = element.find('li', attrs={'data-type':'first-registration'}).text
        except:
            Year = ""
        year.append(Year)
        try:
            Kms = element.find('li', attrs={"data-type" : "mileage"}).text
        except:
            Kms = ""
        kms.append(Kms)

        try:
            Gear = element.find('li', attrs={"data-type":"transmission-type"}).text
        except:
            Gear = ""
        gear.append(Gear)

        try:
            Fuel = element.find('li', attrs={"class":"summary_item_no_bottom_line"}).text
        except:
            Fuel = ""
        fuel.append(Fuel)

        try:
            Fuel_cons = element.find('li', attrs={"data-type":"combined-consumption"}).text
        except:
            Fuel_cons = ""
        fuel_cons.append(Fuel_cons)

        try:
            Co2 = element.find('li', attrs={"data-type":"co2-emission"}).text
        except:
            Co2 = ""
        co2.append(Co2)

        try:
            Prev_owners = element.find('li', attrs={"data-type" : "previous-owners"}).text
        except:
            Prev_owners = ""
        prev_owners.append(Prev_owners)
        try:
            Price = element.find('span', attrs={"class":"cldt-price sc-font-xl sc-font-bold"}).text
        except:
            Price = ""
        price.append(Price)

        try:
            Hp = element.find('li', text =re.compile(r'CV')).text
        except:
            Hp = ""
        hp.append(Hp)
        
        try:
            Location = element.find('span', attrs={"class":"cldf-summary-seller-contact-zip-city"}).text
        except:
            Location = ""
        location.append(Location)

In [35]:
#Creating the Van_Cars_DataFrame
van_cars_df = pd.DataFrame({"Title":title,
                        "Version":version,
                        "Year": year,
                        "Kms": kms,
                        "Hp": hp,
                        "Fuel_type": fuel,
                        "Gear_type": gear,
                        "Fuel_cons": fuel_cons,
                        "CO2_g/Km": co2,
                        "Previous_owners": prev_owners,
                        "City_ZIP" : location,
                        "Price_EUR": price,
                        "Category" : "Van",
                        "Doors" : "3"})

In [36]:
van_cars_df

,Title,Version,Year,Kms,Hp,Fuel_type,Gear_type,Fuel_cons,CO2_g/Km,Previous_owners,City_ZIP,Price_EUR,Category,Doors
0,Ford,TRANSIT CARROZADO,,,\n114 kW (155 CV)\n,\nDiésel\n,\nManual\n,,\n- (g/km)\n,,31192 MUTILVA,"\n€ 16,-\n",Van,3
1,Citroen,BERLINGO 2.0 HDI LEADER,,,\n66 kW (90 CV)\n,\nDiésel\n,\nManual\n,,\n- (g/km)\n,,02006 ALBACETE,"\n€ 1.990,-\n",Van,3
2,Fiat,Fiorino 1.3MJET FURGON,,,\n55 kW (75 CV)\n,\nDiésel\n,\nManual\n,,\n- (g/km)\n,,08921 BADALONA,"\n€ 2.980,-\n",Van,3
3,Renault,Kangoo 1.9D Gran Volumen 65,,,\n47 kW (64 CV)\n,\nDiésel\n,\nManual\n,,\n- (g/km)\n,,48270 MARKINA,"\n€ 3.100,-\n",Van,3
4,Fiat,Dobló Combi 1.3Mjt Actual,,,\n55 kW (75 CV)\n,\nDiésel\n,\nManual\n,,\n- (g/km)\n,,28359 TITULCIA,"\n€ 3.500,-\n",Van,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,Renault,Kangoo Fg. Compact 1.5dCi Prof. 75 E5,,,\n55 kW (75 CV)\n,\nDiésel\n,\nManual\n,,\n- (g/km)\n,,28939 ARROYOMOLINOS,"\n€ 3.990,-\n",Van,3
396,Ford,FT 300M Van 100,,,\n74 kW (101 CV)\n,\nDiésel\n,\nManual\n,,\n- (g/km)\n,,46930 QUART DE POBLET,"\n€ 3.990,-\n",Van,3
397,Volkswagen,Transporter Kombi 2 2.4 Syncro 78,,,\n57 kW (77 CV)\n,\nDiésel\n,\nManual\n,,\n- (g/km)\n,,28232 LAS ROZAS,"\n€ 3.990,-\n",Van,3
398,Volkswagen,Caddy 1.9TDI Kombi 75,,,\n55 kW (75 CV)\n,\nDiésel\n,\nManual\n,,\n- (g/km)\n,,29750 Algarrobo-Costa,"\n€ 3.990,-\n",Van,3
399,Peugeot Expert,Furgón 2.0HDI Acristalado 230 C 110,\n10/2005\n,\n249.000 km\n,\n81 kW (110 CV)\n,\nDiésel\n,\nManual\n,"\n6,4 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,,"\n€ 3.990,-\nIVA deducible\n",Van,3

In [37]:
#Defining columns for Other cars
title = []
version = []
year = []
kms = []
hp = []
gear = []
fuel = []
fuel_cons = []
co2 =[]
prev_owners = []
price = []
location = []

In [38]:
#Scapping Other cars

for other_cars_page in all_pages:
    
    other_cars_page = requests.get("https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=" + str(other_cars_page) + "&cy=E&body=7&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&")
    other_cars_soup = BeautifulSoup(other_cars_page.text,"lxml")
    other_cars_ads = other_cars_soup.find_all('div', attrs={"class": "cl-list-element cl-list-element-gap"})
    
    sleep(randint(2,10))
    
    for element in other_cars_ads:
        try:
            Title = element.find('h2', attrs={"class":'cldt-summary-makemodel sc-font-bold sc-ellipsis'}).text
        except:
            Title = ""
        title.append(Title)
        
        try:
            Version = element.find('h2', attrs={"class":"cldt-summary-version sc-ellipsis"}).text
        except:
            Version = ""
        version.append(Version)
        try:
            Year = element.find('li', attrs={'data-type':'first-registration'}).text
        except:
            Year = ""
        year.append(Year)
        try:
            Kms = element.find('li', attrs={"data-type" : "mileage"}).text
        except:
            Kms = ""
        kms.append(Kms)

        try:
            Gear = element.find('li', attrs={"data-type":"transmission-type"}).text
        except:
            Gear = ""
        gear.append(Gear)

        try:
            Fuel = element.find('li', attrs={"class":"summary_item_no_bottom_line"}).text
        except:
            Fuel = ""
        fuel.append(Fuel)

        try:
            Fuel_cons = element.find('li', attrs={"data-type":"combined-consumption"}).text
        except:
            Fuel_cons = ""
        fuel_cons.append(Fuel_cons)

        try:
            Co2 = element.find('li', attrs={"data-type":"co2-emission"}).text
        except:
            Co2 = ""
        co2.append(Co2)

        try:
            Prev_owners = element.find('li', attrs={"data-type" : "previous-owners"}).text
        except:
            Prev_owners = ""
        prev_owners.append(Prev_owners)
        try:
            Price = element.find('span', attrs={"class":"cldt-price sc-font-xl sc-font-bold"}).text
        except:
            Price = ""
        price.append(Price)

        try:
            Hp = element.find('li', text =re.compile(r'CV')).text
        except:
            Hp = ""
        hp.append(Hp)
        
        try:
            Location = element.find('span', attrs={"class":"cldf-summary-seller-contact-zip-city"}).text
        except:
            Location = ""
        location.append(Location)

In [39]:
#Creating the Other_Cars_DataFrame
other_cars_df = pd.DataFrame({"Title":title,
                        "Version":version,
                        "Year": year,
                        "Kms": kms,
                        "Hp": hp,
                        "Fuel_type": fuel,
                        "Gear_type": gear,
                        "Fuel_cons": fuel_cons,
                        "CO2_g/Km": co2,
                        "Previous_owners": prev_owners,
                        "City_ZIP" : location,
                        "Price_EUR": price,
                        "Category" : "Other",
                        "Doors" : ""})

In [40]:
#Mergin all DataFrames 
all_cars_df = pd.concat([small_cars_df,
                         sedan_cars_df,
                         familiar_cars_df,
                         minivan_cars_df,
                         coupe_cars_df,
                         cabrio_cars_df,
                         suv_cars_df,
                         van_cars_df,
                         other_cars_df], axis = 0)
#Reset_index
all_cars_df = all_cars_df.reset_index()

In [41]:
all_cars_df.drop(["index"],axis = 1)

,Title,Version,Year,Kms,Hp,Fuel_type,Gear_type,Fuel_cons,CO2_g/Km,Previous_owners,City_ZIP,Price_EUR,Category,Doors
0,SEAT Cordoba,1.9 TDi Sport 90,\n12/2000\n,\n254.000 km\n,\n66 kW (90 CV)\n,\nDiésel\n,\nManual\n,"\n4,9 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,18195 CULLAR VEGA,"\n€ 980,-\nIVA deducible\n",Small,5
1,Rover 25,1.6 Classic,\n01/2001\n,\n171.720 km\n,\n80 kW (109 CV)\n,\nGasolina\n,\nManual\n,\n6 l/100 km (mixto)\nPuede obtenerse informac...,\n- (g/km)\n,\n- (Propietarios)\n,28045 MADRID,"\n€ 1.290,-\n",Small,5
2,SEAT Arosa,1.0 Stylo,\n06/1998\n,\n110.000 km\n,\n37 kW (50 CV)\n,\nGasolina\n,\nManual\n,"\n5,7 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,46940 MANISES,"\n€ 1.450,-\n",Small,5
3,Daewoo Lanos,1.6 16v. SX,\n06/2000\n,\n185.000 km\n,\n78 kW (106 CV)\n,\nGasolina\n,\nManual\n,"\n8,2 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,46940 MANISES,"\n€ 1.500,-\n",Small,5
4,Fiat Panda,1.2 Alessi,\n06/2006\n,\n190.000 km\n,\n44 kW (60 CV)\n,\nGasolina\n,\nManual\n,"\n5,6 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,46940 MANISES,"\n€ 1.950,-\n",Small,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,Chevrolet G,,\n03/1935\n,\n650.000 km\n,\n59 kW (80 CV)\n,\nGasolina\n,\n- (Cambio)\n,\n- (l/100 km)\n,\n- (g/km)\n,\n- (Propietarios)\n,,"\n€ 16.500,-\n",Other,
3596,Pontiac Trans Am,GTA,\n07/1991\n,\n71.000 km\n,\n170 kW (231 CV)\n,\nGasolina\n,\n- (Cambio)\n,\n- (l/100 km)\n,\n- (g/km)\n,\n- (Propietarios)\n,,"\n€ 16.500,-\n",Other,
3597,Volvo C70,T5 summum,\n02/2011\n,\n71.000 km\n,\n240 kW (326 CV)\n,\nGasolina\n,\n- (Cambio)\n,\n- (l/100 km)\n,\n- (g/km)\n,\n- (Propietarios)\n,,"\n€ 16.500,-\n",Other,
3598,SEAT Leon,Cupra R,\n10/2011\n,\n88.000 km\n,\n195 kW (265 CV)\n,\nGasolina\n,\n- (Cambio)\n,\n- (l/100 km)\n,\n- (g/km)\n,\n- (Propietarios)\n,,"\n€ 16.500,-\n",Other,
3599,Volkswagen,Modificada,\n12/2005\n,\n158.000 km\n,\n184 kW (250 CV)\n,\nGasolina\n,\nAutomático\n,\n- (l/100 km)\n,\n- (g/km)\n,\n2 Propietarios\n,,"\n€ 16.500,-\nIVA deducible\n",Other,

In [42]:
all_cars_df.to_csv('/users/alfon/Desktop/Master/TFM/Csv/cars_raw.csv', header=True, index=False)