In [1]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
import re
import matplotlib.pyplot as plt

from time import sleep
from random import randint

In [2]:
# The website from where we are going to obtain the data
main_url = "https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=1&cy=E&atype=C&recommended_sorting_based_id=63264e9a-86be-4fce-8e45-42cfcd1def1a&"

In [3]:
# Links for the different categories
small_cars_url = "https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=1&cy=E&body=1&atype=C&recommended_sorting_based_id=63264e9a-86be-4fce-8e45-42cfcd1def1a&"
sedan_cars_url = "https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=1&cy=E&body=6&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&"
familiar_cars_url = "https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=1&cy=E&body=5&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&"
minivan_cars_url = "https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=1&cy=E&body=12&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&"
coupe_cars_url = "https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=1&cy=E&body=3&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&"
cabrio_cars_url = "https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=1&cy=E&body=2&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&"
suv_cars_url = "https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=1&cy=E&body=4&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&"
van_cars_url = "https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=1&cy=E&body=13&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&"
other_cars_url = "https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=1&cy=E&body=7&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&"

In [4]:
#Defining columns for small cars
title = []
version = []
year = []
kms = []
hp = []
gear = []
fuel = []
fuel_cons = []
co2 =[]
prev_owners = []
price = []
location = []

In [5]:
# Analysing urls for the diffenret pages:
# url_pag1 = "https://www.autoscout24.es/lst/?sort=standard&desc=0&ustate=N%2CU&size=20&page=1&cy=E&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&"
# url_pag2 = "https://www.autoscout24.es/lst/?sort=standard&desc=0&ustate=N%2CU&size=20&page=2&cy=E&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&"
# url_pag3 = "https://www.autoscout24.es/lst/?sort=standard&desc=0&ustate=N%2CU&size=20&page=3&cy=E&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&"

# Max page per url = 20 (start: page 1, stop: page 21 -1, step: 1 by 1 as the url changes from page=n to page=n+1 from one page to the following

all_pages = np.arange(1,21,1)

In [6]:
#Scapping small cars

for small_cars_page in all_pages:
    
    small_cars_page = requests.get("https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=" + str(small_cars_page) + "&cy=E&body=1&atype=C&recommended_sorting_based_id=63264e9a-86be-4fce-8e45-42cfcd1def1a&")
    small_cars_soup = BeautifulSoup(small_cars_page.text,"lxml")
    small_cars_ads = small_cars_soup.find_all('div', attrs={"class": "cl-list-element cl-list-element-gap"})
    
    sleep(randint(2,10))
    
    for element in small_cars_ads:
        try:
            Title = element.find('h2', attrs={"class":'cldt-summary-makemodel sc-font-bold sc-ellipsis'}).text
        except:
            Title = "Nan"
        title.append(Title)
        
        try:
            Version = element.find('h2', attrs={"class":"cldt-summary-version sc-ellipsis"}).text
        except:
            Version = "Nan"
        version.append(Version)
        try:
            Year = element.find('li', attrs={'data-type':'first-registration'}).text
        except:
            Year = "Nan"
        year.append(Year)
        try:
            Kms = element.find('li', attrs={"data-type" : "mileage"}).text
        except:
            Kms = "Nan"
        kms.append(Kms)

        try:
            Gear = element.find('li', attrs={"data-type":"transmission-type"}).text
        except:
            Gear = "Nan"
        gear.append(Gear)

        try:
            Fuel = element.find('li', attrs={"class":"summary_item_no_bottom_line"}).text
        except:
            Fuel = "Nan"
        fuel.append(Fuel)

        try:
            Fuel_cons = element.find('li', attrs={"data-type":"combined-consumption"}).text
        except:
            Fuel_cons = "Nan"
        fuel_cons.append(Fuel_cons)

        try:
            Co2 = element.find('li', attrs={"data-type":"co2-emission"}).text
        except:
            Co2 = "Nan"
        co2.append(Co2)

        try:
            Prev_owners = element.find('li', attrs={"data-type" : "previous-owners"}).text
        except:
            Prev_owners = "Nan"
        prev_owners.append(Prev_owners)
        try:
            Price = element.find('span', attrs={"class":"cldt-price sc-font-xl sc-font-bold"}).text
        except:
            Price = "Nan"
        price.append(Price)

        try:
            Hp = element.find('li', text =re.compile(r'CV')).text
        except:
            Hp = "Nan"
        hp.append(Hp)
        
        try:
            Location = element.find('span', attrs={"class":"cldf-summary-seller-contact-zip-city"}).text
        except:
            Location = "Nan"
        location.append(Location)

In [7]:
#Creating the Small_Cars_DataFrame
small_cars_df = pd.DataFrame({"Title":title,
                        "Version":version,
                        "Year": year,
                        "Kms": kms,
                        "Hp": hp,
                        "Fuel_type": fuel,
                        "Gear_type": gear,
                        "Fuel_l/100km": fuel_cons,
                        "CO2_g/Km": co2,
                        "Previous_owners": prev_owners,
                        "City_ZIP" : location,
                        "Price_EUR": price,
                        "Category" : "Peque√±o",
                        "Doors" : "5"})

In [8]:
small_cars_df

,Title,Version,Year,Kms,Hp,Fuel_type,Gear_type,Fuel_l/100km,CO2_g/Km,Previous_owners,City_ZIP,Price_EUR,Category,Doors
0,SEAT Cordoba,1.9 TDi Sport 90,\n12/2000\n,\n254.000 km\n,\n66 kW (90 CV)\n,\nDi√©sel\n,\nManual\n,"\n4,9 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,18195 CULLAR VEGA,"\n‚Ç¨ 980,-\nIVA deducible\n",Peque√±o,5
1,Renault Megane,1.6 Century,\n08/2001\n,\n190.000 km\n,\n82 kW (111 CV)\n,\nGasolina\n,\nManual\n,\n7 l/100 km (mixto)\nPuede obtenerse informac...,\n- (g/km)\n,\n- (Propietarios)\n,28891 VELILLA DE SAN ANTONIO,"\n‚Ç¨ 1.500,-\n",Peque√±o,5
2,Daewoo Lanos,1.6 16v. SX,\n06/2000\n,\n185.000 km\n,\n78 kW (106 CV)\n,\nGasolina\n,\nManual\n,"\n8,2 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,46940 MANISES,"\n‚Ç¨ 1.500,-\n",Peque√±o,5
3,SEAT Ibiza,1.4 Stella,\n11/2001\n,\n167.577 km\n,\n44 kW (60 CV)\n,\nGasolina\n,\nManual\n,"\n6,6 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,08310 ARGENTONA,"\n‚Ç¨ 1.600,-\n",Peque√±o,5
4,Alfa Romeo 145,1.6 TS Lujo 16v,\n04/1997\n,\n127.000 km\n,\n88 kW (120 CV)\n,\nGasolina\n,\nManual\n,"\n7,8 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,46940 MANISES,"\n‚Ç¨ 1.850,-\n",Peque√±o,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,Alfa Romeo 147,3.2 GTA,\n01/2005\n,\n44.000 km\n,\n184 kW (250 CV)\n,\nGasolina\n,\nManual\n,"\n12,1 l/100 km (mixto)\nPuede obtenerse infor...",\n- (g/km)\n,\n- (Propietarios)\n,08030 BARCELONA,"\n‚Ç¨ 25.900,-\n",Peque√±o,5
396,BMW 120,iA,\n06/2018\n,\n18.000 km\n,\n135 kW (184 CV)\n,\nGasolina\n,\nAutom√°tico\n,"\n5,9 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,28982 PARLA,"\n‚Ç¨ 25.990,-\n",Peque√±o,5
397,Volkswagen Golf GTI,2.0 TSI GTI DSG6 169kW,\n04/2018\n,\n95.658 km\n,\n169 kW (230 CV)\n,\nGasolina\n,\nAutom√°tico\n,"\n6,3 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,11500 EL PUERTO DE SANTA MAR√çA,"\n‚Ç¨ 25.990,-\nIVA deducible\n",Peque√±o,5
398,BMW 116,d,\n09/2020\n,\n19.294 km\n,\n85 kW (116 CV)\n,\nDi√©sel\n,\nManual\n,"\n3,8 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,8223 terrassa,"\n‚Ç¨ 26.000,-\n",Peque√±o,5
399,BMW 116,d,\n09/2020\n,\n9.862 km\n,\n85 kW (116 CV)\n,\nDi√©sel\n,\nAutom√°tico\n,"\n3,8 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,8223 terrassa,"\n‚Ç¨ 26.000,-\n",Peque√±o,5

In [9]:
#Defining columns for sedan cars
title = []
version = []
year = []
kms = []
hp = []
gear = []
fuel = []
fuel_cons = []
co2 =[]
prev_owners = []
price = []
location = []

In [10]:
#Scapping sedan cars

for sedan_cars_page in all_pages:
    
    sedan_cars_page = requests.get("https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=" + str(sedan_cars_page) + "&cy=E&body=6&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&")
    sedan_cars_soup = BeautifulSoup(sedan_cars_page.text,"lxml")
    sedan_cars_ads = sedan_cars_soup.find_all('div', attrs={"class": "cl-list-element cl-list-element-gap"})
    
    sleep(randint(2,10))
    
    for element in sedan_cars_ads:
        try:
            Title = element.find('h2', attrs={"class":'cldt-summary-makemodel sc-font-bold sc-ellipsis'}).text
        except:
            Title = "Nan"
        title.append(Title)
        
        try:
            Version = element.find('h2', attrs={"class":"cldt-summary-version sc-ellipsis"}).text
        except:
            Version = "Nan"
        version.append(Version)
        try:
            Year = element.find('li', attrs={'data-type':'first-registration'}).text
        except:
            Year = "Nan"
        year.append(Year)
        try:
            Kms = element.find('li', attrs={"data-type" : "mileage"}).text
        except:
            Kms = "Nan"
        kms.append(Kms)

        try:
            Gear = element.find('li', attrs={"data-type":"transmission-type"}).text
        except:
            Gear = "Nan"
        gear.append(Gear)

        try:
            Fuel = element.find('li', attrs={"class":"summary_item_no_bottom_line"}).text
        except:
            Fuel = "Nan"
        fuel.append(Fuel)

        try:
            Fuel_cons = element.find('li', attrs={"data-type":"combined-consumption"}).text
        except:
            Fuel_cons = "Nan"
        fuel_cons.append(Fuel_cons)

        try:
            Co2 = element.find('li', attrs={"data-type":"co2-emission"}).text
        except:
            Co2 = "Nan"
        co2.append(Co2)

        try:
            Prev_owners = element.find('li', attrs={"data-type" : "previous-owners"}).text
        except:
            Prev_owners = "Nan"
        prev_owners.append(Prev_owners)
        try:
            Price = element.find('span', attrs={"class":"cldt-price sc-font-xl sc-font-bold"}).text
        except:
            Price = "Nan"
        price.append(Price)

        try:
            Hp = element.find('li', text =re.compile(r'CV')).text
        except:
            Hp = "Nan"
        hp.append(Hp)
        
        try:
            Location = element.find('span', attrs={"class":"cldf-summary-seller-contact-zip-city"}).text
        except:
            Location = "Nan"
        location.append(Location)

In [11]:
#Creating the Sedan_Cars_DataFrame
sedan_cars_df = pd.DataFrame({"Title":title,
                        "Version":version,
                        "Year": year,
                        "Kms": kms,
                        "Hp": hp,
                        "Fuel_type": fuel,
                        "Gear_type": gear,
                        "Fuel_l/100km": fuel_cons,
                        "CO2_g/Km": co2,
                        "Previous_owners": prev_owners,
                        "City_ZIP" : location,
                        "Price_EUR": price,
                        "Category" : "Sedan",
                        "Doors" : "5"})

In [12]:
sedan_cars_df

,Title,Version,Year,Kms,Hp,Fuel_type,Gear_type,Fuel_l/100km,CO2_g/Km,Previous_owners,City_ZIP,Price_EUR,Category,Doors
0,Audi A6,2.3,\n11/1995\n,\n291.000 km\n,\n98 kW (133 CV)\n,\nGasolina\n,\nManual\n,\n0 l/100 km (mixto)\nPuede obtenerse informac...,\n- (g/km)\n,\n- (Propietarios)\n,41003 SEVILLA,"\n‚Ç¨ 1.120,-\n",Sedan,5
1,Peugeot 406,1.9 SRSD,\n06/1998\n,\n150.000 km\n,\n68 kW (92 CV)\n,\nDi√©sel\n,\nManual\n,"\n6,4 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,28021 MADRID,"\n‚Ç¨ 1.200,-\n",Sedan,5
2,Lancia Dedra,1.8 i.e. LE,\n06/1994\n,\n84.000 km\n,\n78 kW (106 CV)\n,\nGasolina\n,\nManual\n,\n0 l/100 km (mixto)\nPuede obtenerse informac...,\n- (g/km)\n,\n- (Propietarios)\n,26500 CALAHORRA,"\n‚Ç¨ 1.499,-\n",Sedan,5
3,Fiat Marea,1.9 TD 100 SX,\n10/1999\n,\n158.994 km\n,\n74 kW (101 CV)\n,\nDi√©sel\n,\nManual\n,"\n6,2 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,48970 BASAURI,"\n‚Ç¨ 1.500,-\n",Sedan,5
4,Opel Vectra,1.9CDTI 8v Design,\n06/2005\n,\n149.000 km\n,\n88 kW (120 CV)\n,\nDi√©sel\n,\nManual\n,"\n6,5 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,28936 MOSTOLES,"\n‚Ç¨ 1.950,-\n",Sedan,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,Mercedes-Benz E 220,E 220d 9G-Tronic 194,\n09/2016\n,\n90.839 km\n,\n143 kW (194 CV)\n,\nDi√©sel\n,\nAutom√°tico\n,"\n3,9 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,23400 UBEDA,"\n‚Ç¨ 27.900,-\n",Sedan,5
396,BMW 525,d,\n04/2017\n,\n137.603 km\n,\n140 kW (190 CV)\n,\nDi√©sel\n,\nManual\n,"\n4,5 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,09001 BURGOS,"\n‚Ç¨ 27.990,-\n",Sedan,5
397,Audi A6,3.0TDI quattro S-Tronic 200kW,\n06/2015\n,\n52.134 km\n,\n200 kW (272 CV)\n,\nDi√©sel\n,\nAutom√°tico\n,"\n5,1 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,09001 BURGOS,"\n‚Ç¨ 27.990,-\n",Sedan,5
398,BMW X6 M,116da M Packet,\n11/2020\n,\n12.514 km\n,\n85 kW (116 CV)\n,\nDi√©sel\n,\nAutom√°tico\n,\n- (l/100 km)\n,\n- (g/km)\n,\n- (Propietarios)\n,28914 Legan√©s,"\n‚Ç¨ 27.990,-\n",Sedan,5
399,Audi A5,Sportback 2.0TDI Sport S tronic 110kW,\n01/2018\n,\n56.736 km\n,\n110 kW (150 CV)\n,\nDi√©sel\n,\nAutom√°tico\n,"\n4,2 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,46970 ALAQU√ÅS,"\n‚Ç¨ 27.995,-\n",Sedan,5

In [13]:
#Defining columns for familiar cars
title = []
version = []
year = []
kms = []
hp = []
gear = []
fuel = []
fuel_cons = []
co2 =[]
prev_owners = []
price = []
location = []

In [14]:
#Scapping familiar cars

for familiar_cars_page in all_pages:
    
    familiar_cars_page = requests.get("https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=" + str(familiar_cars_page) + "&cy=E&body=5&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&")
    familiar_cars_soup = BeautifulSoup(familiar_cars_page.text,"lxml")
    familiar_cars_ads = familiar_cars_soup.find_all('div', attrs={"class": "cl-list-element cl-list-element-gap"})
    
    sleep(randint(2,10))
    
    for element in familiar_cars_ads:
        try:
            Title = element.find('h2', attrs={"class":'cldt-summary-makemodel sc-font-bold sc-ellipsis'}).text
        except:
            Title = "Nan"
        title.append(Title)
        
        try:
            Version = element.find('h2', attrs={"class":"cldt-summary-version sc-ellipsis"}).text
        except:
            Version = "Nan"
        version.append(Version)
        try:
            Year = element.find('li', attrs={'data-type':'first-registration'}).text
        except:
            Year = "Nan"
        year.append(Year)
        try:
            Kms = element.find('li', attrs={"data-type" : "mileage"}).text
        except:
            Kms = "Nan"
        kms.append(Kms)

        try:
            Gear = element.find('li', attrs={"data-type":"transmission-type"}).text
        except:
            Gear = "Nan"
        gear.append(Gear)

        try:
            Fuel = element.find('li', attrs={"class":"summary_item_no_bottom_line"}).text
        except:
            Fuel = "Nan"
        fuel.append(Fuel)

        try:
            Fuel_cons = element.find('li', attrs={"data-type":"combined-consumption"}).text
        except:
            Fuel_cons = "Nan"
        fuel_cons.append(Fuel_cons)

        try:
            Co2 = element.find('li', attrs={"data-type":"co2-emission"}).text
        except:
            Co2 = "Nan"
        co2.append(Co2)

        try:
            Prev_owners = element.find('li', attrs={"data-type" : "previous-owners"}).text
        except:
            Prev_owners = "Nan"
        prev_owners.append(Prev_owners)
        try:
            Price = element.find('span', attrs={"class":"cldt-price sc-font-xl sc-font-bold"}).text
        except:
            Price = "Nan"
        price.append(Price)

        try:
            Hp = element.find('li', text =re.compile(r'CV')).text
        except:
            Hp = "Nan"
        hp.append(Hp)
        
        try:
            Location = element.find('span', attrs={"class":"cldf-summary-seller-contact-zip-city"}).text
        except:
            Location = "Nan"
        location.append(Location)

In [15]:
#Creating the Familiar_Cars_DataFrame
familiar_cars_df = pd.DataFrame({"Title":title,
                        "Version":version,
                        "Year": year,
                        "Kms": kms,
                        "Hp": hp,
                        "Fuel_type": fuel,
                        "Gear_type": gear,
                        "Fuel_l/100km": fuel_cons,
                        "CO2_g/Km": co2,
                        "Previous_owners": prev_owners,
                        "City_ZIP" : location,
                        "Price_EUR": price,
                        "Category" : "Familiar",
                        "Doors" : "5"})

In [16]:
familiar_cars_df

,Title,Version,Year,Kms,Hp,Fuel_type,Gear_type,Fuel_l/100km,CO2_g/Km,Previous_owners,City_ZIP,Price_EUR,Category,Doors
0,Volvo 850,Estate 2.0 10v,\n06/1995\n,\n128.000 km\n,\n93 kW (126 CV)\n,\nGasolina\n,\nManual\n,\n0 l/100 km (mixto)\nPuede obtenerse informac...,\n- (g/km)\n,\n- (Propietarios)\n,03580 ALFAZ DEL PI,"\n‚Ç¨ 2.490,-\n",Familiar,5
1,Opel Astra,SW 1.7CDTi Enjoy 6vel.,\n03/2007\n,\n197.300 km\n,\n73 kW (99 CV)\n,\nDi√©sel\n,\nManual\n,\n5 l/100 km (mixto)\nPuede obtenerse informac...,\n- (g/km)\n,\n- (Propietarios)\n,48960 GALDAKAO,"\n‚Ç¨ 2.490,-\n",Familiar,5
2,BMW Active Hybrid 3,E46 COMPACT,\n10/2003\n,\n381.883 km\n,\n110 kW (150 CV)\n,\nDi√©sel\n,\nManual\n,\n- (l/100 km)\n,\n- (g/km)\n,\n- (Propietarios)\n,30161 Llano de Brujas,"\n‚Ç¨ 2.900,-\n",Familiar,5
3,BMW 320,d Touring,\n10/2006\n,\n524.290 km\n,\n120 kW (163 CV)\n,\nDi√©sel\n,\nManual\n,"\n5,9 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,03006 ALICANTE,"\n‚Ç¨ 3.600,-\n",Familiar,5
4,Volkswagen Golf,Variant 1.9TDI Highline Bluemotion,\n10/2008\n,\n417.000 km\n,\n77 kW (105 CV)\n,\nDi√©sel\n,\nManual\n,"\n4,6 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,28043 MADRID,"\n‚Ç¨ 3.850,-\n",Familiar,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,Mazda 6,6 Wagon 2.2 Skyactiv-D Zenith 110kW,\n01/2020\n,\n16.490 km\n,\n110 kW (150 CV)\n,\nDi√©sel\n,\nManual\n,"\n4,5 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,18015 GRANADA,"\n‚Ç¨ 23.490,-\n",Familiar,5
396,Mercedes-Benz CLA 200,d Shooting Brake,\n05/2017\n,\n89.580 km\n,\n100 kW (136 CV)\n,\nDi√©sel\n,\nManual\n,"\n4,3 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,36860 PONTEAEREAS,"\n‚Ç¨ 23.500,-\n",Familiar,5
397,Mercedes-Benz CLA 220,d Shooting Brake 7G-DCT,\n10/2016\n,\n63.665 km\n,\n130 kW (177 CV)\n,\nDi√©sel\n,\nAutom√°tico\n,"\n4,2 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,28022 madrid,"\n‚Ç¨ 23.500,-\n",Familiar,5
398,Peugeot 508,SW 1.5 BlueHDi S&S Allure EAT8 130,\n09/2019\n,\n50.775 km\n,\n96 kW (131 CV)\n,\nDi√©sel\n,\nAutom√°tico\n,"\n3,6 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,46006 VALENCIA,"\n‚Ç¨ 23.800,-\n",Familiar,5
399,Renault Megane,E-TECH Zen 117kW,\n09/2020\n,\n8.669 km\n,\n117 kW (159 CV)\n,\nElectro/Gasolina\n,\nAutom√°tico\n,\n0 l/100 km (mixto)\nPuede obtenerse informac...,\n- (g/km)\n,\n- (Propietarios)\n,39011 SANTANDER,"\n‚Ç¨ 23.990,-\n",Familiar,5

In [17]:
#Defining columns for minivan cars
title = []
version = []
year = []
kms = []
hp = []
gear = []
fuel = []
fuel_cons = []
co2 =[]
prev_owners = []
price = []
location = []

In [18]:
#Scapping minivans cars

for minivan_cars_page in all_pages:
    
    minivan_cars_page = requests.get("https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=" + str(minivan_cars_page) + "&cy=E&body=12&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&")
    minivan_cars_soup = BeautifulSoup(minivan_cars_page.text,"lxml")
    minivan_cars_ads = minivan_cars_soup.find_all('div', attrs={"class": "cl-list-element cl-list-element-gap"})
    
    sleep(randint(2,10))
    
    for element in minivan_cars_ads:
        
        try:
            Title = element.find('h2', attrs={"class":'cldt-summary-makemodel sc-font-bold sc-ellipsis'}).text
        except:
            Title = "Nan"
        title.append(Title)
        
        try:
            Version = element.find('h2', attrs={"class":"cldt-summary-version sc-ellipsis"}).text
        except:
            Version = "Nan"
        version.append(Version)
        try:
            Year = element.find('li', attrs={'data-type':'first-registration'}).text
        except:
            Year = "Nan"
        year.append(Year)
        try:
            Kms = element.find('li', attrs={"data-type" : "mileage"}).text
        except:
            Kms = "Nan"
        kms.append(Kms)

        try:
            Gear = element.find('li', attrs={"data-type":"transmission-type"}).text
        except:
            Gear = "Nan"
        gear.append(Gear)

        try:
            Fuel = element.find('li', attrs={"class":"summary_item_no_bottom_line"}).text
        except:
            Fuel = "Nan"
        fuel.append(Fuel)

        try:
            Fuel_cons = element.find('li', attrs={"data-type":"combined-consumption"}).text
        except:
            Fuel_cons = "Nan"
        fuel_cons.append(Fuel_cons)

        try:
            Co2 = element.find('li', attrs={"data-type":"co2-emission"}).text
        except:
            Co2 = "Nan"
        co2.append(Co2)

        try:
            Prev_owners = element.find('li', attrs={"data-type" : "previous-owners"}).text
        except:
            Prev_owners = "Nan"
        prev_owners.append(Prev_owners)
        try:
            Price = element.find('span', attrs={"class":"cldt-price sc-font-xl sc-font-bold"}).text
        except:
            Price = "Nan"
        price.append(Price)

        try:
            Hp = element.find('li', text =re.compile(r'CV')).text
        except:
            Hp = "Nan"
        hp.append(Hp)
        
        try:
            Location = element.find('span', attrs={"class":"cldf-summary-seller-contact-zip-city"}).text
        except:
            Location = "Nan"
        location.append(Location)

In [19]:
#Creating the Minivan_Cars_DataFrame
minivan_cars_df = pd.DataFrame({"Title":title,
                        "Version":version,
                        "Year": year,
                        "Kms": kms,
                        "Hp": hp,
                        "Fuel_type": fuel,
                        "Gear_type": gear,
                        "Fuel_l/100km": fuel_cons,
                        "CO2_g/Km": co2,
                        "Previous_owners": prev_owners,
                        "City_ZIP" : location,
                        "Price_EUR": price,
                        "Category" : "Monovolumen",
                        "Doors" : "5"})

In [20]:
minivan_cars_df

,Title,Version,Year,Kms,Hp,Fuel_type,Gear_type,Fuel_l/100km,CO2_g/Km,Previous_owners,City_ZIP,Price_EUR,Category,Doors
0,Renault Espace,2.2 dCi Expression,\n07/2004\n,\n267.000 km\n,\n110 kW (150 CV)\n,\nDi√©sel\n,\nManual\n,"\n7,7 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,29004 MALAGA,"\n‚Ç¨ 3.250,-\n",Monovolumen,5
1,SEAT Altea XL,XL 1.9TDI Reference,\n01/2010\n,\n233.209 km\n,\n77 kW (105 CV)\n,\nDi√©sel\n,\nManual\n,"\n5,4 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,46930 QUART DE POBLET,"\n‚Ç¨ 3.400,-\n",Monovolumen,5
2,Mercedes-Benz B 200,CDI Autotronic,\n07/2007\n,\n280.000 km\n,\n102 kW (139 CV)\n,\nDi√©sel\n,\nAutom√°tico\n,"\n5,6 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,48940 LEIOA,"\n‚Ç¨ 3.690,-\n",Monovolumen,5
3,Citroen C4,Grand Picasso 1.6HDI Exclusive CMP,\n01/2009\n,\n252.739 km\n,\n80 kW (109 CV)\n,\nDi√©sel\n,\nAutom√°tico\n,"\n5,4 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,08310 ARGENTONA,"\n‚Ç¨ 3.700,-\n",Monovolumen,5
4,SEAT Altea XL,XL I-Tech Ecomotive,\n09/2014\n,\n283.115 km\n,\n76 kW (103 CV)\n,\nDi√©sel\n,\nManual\n,\n- (l/100 km)\n,\n- (g/km)\n,\n- (Propietarios)\n,08280 CALAF,"\n‚Ç¨ 3.900,-\n",Monovolumen,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,Renault Megane,1.9dCi Century,\n06/2003\n,\n255.000 km\n,\n77 kW (105 CV)\n,\nDi√©sel\n,\nManual\n,"\n6,4 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,46940 MANISES,"\n‚Ç¨ 1.950,-\n",Monovolumen,5
396,Renault Scenic,II 1.6 Confort Expression,\n05/2003\n,\n220.000 km\n,\n84 kW (114 CV)\n,\nGasolina\n,\nManual\n,"\n7,2 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,43850 CAMBRILS,"\n‚Ç¨ 1.990,-\n",Monovolumen,5
397,Opel Agila,1.2 16v Cosmo 80,\n05/2006\n,\n127.000 km\n,\n58 kW (79 CV)\n,\nGasolina\n,\nManual\n,\n6 l/100 km (mixto)\nPuede obtenerse informac...,\n- (g/km)\n,\n- (Propietarios)\n,08001 Barcelona,"\n‚Ç¨ 1.990,-\n",Monovolumen,5
398,Peugeot 1007,1.4HDI Urban,\n11/2005\n,\n174.000 km\n,\n51 kW (69 CV)\n,\nDi√©sel\n,\nManual\n,"\n4,7 l/100 km (mixto)\nPuede obtenerse inform...",\n124 g/km (mixto)\nPuede obtenerse informaci√≥...,\n- (Propietarios)\n,Nan,"\n‚Ç¨ 1.990,-\n",Monovolumen,5
399,Citroen Xsara,Picasso 2.0HDi SX Plus,\n03/2002\n,\n252.300 km\n,\n66 kW (90 CV)\n,\nDi√©sel\n,\nManual\n,"\n5,5 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,48960 GALDAKAO,"\n‚Ç¨ 1.990,-\n",Monovolumen,5

In [21]:
#Defining columns for coupe cars
title = []
version = []
year = []
kms = []
hp = []
gear = []
fuel = []
fuel_cons = []
co2 =[]
prev_owners = []
price = []
location = []

In [22]:
#Scapping coupe cars

for coupe_cars_page in all_pages:
    
    coupe_cars_page = requests.get("https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=" + str(coupe_cars_page) + "&cy=E&body=3&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&")
    coupe_cars_soup = BeautifulSoup(coupe_cars_page.text,"lxml")
    coupe_cars_ads = coupe_cars_soup.find_all('div', attrs={"class": "cl-list-element cl-list-element-gap"})
    
    sleep(randint(2,10))
    
    for element in coupe_cars_ads:
        try:
            Title = element.find('h2', attrs={"class":'cldt-summary-makemodel sc-font-bold sc-ellipsis'}).text
        except:
            Title = "Nan"
        title.append(Title)
        
        try:
            Version = element.find('h2', attrs={"class":"cldt-summary-version sc-ellipsis"}).text
        except:
            Version = "Nan"
        version.append(Version)
        try:
            Year = element.find('li', attrs={'data-type':'first-registration'}).text
        except:
            Year = "Nan"
        year.append(Year)
        try:
            Kms = element.find('li', attrs={"data-type" : "mileage"}).text
        except:
            Kms = "Nan"
        kms.append(Kms)

        try:
            Gear = element.find('li', attrs={"data-type":"transmission-type"}).text
        except:
            Gear = "Nan"
        gear.append(Gear)

        try:
            Fuel = element.find('li', attrs={"class":"summary_item_no_bottom_line"}).text
        except:
            Fuel = "Nan"
        fuel.append(Fuel)

        try:
            Fuel_cons = element.find('li', attrs={"data-type":"combined-consumption"}).text
        except:
            Fuel_cons = "Nan"
        fuel_cons.append(Fuel_cons)

        try:
            Co2 = element.find('li', attrs={"data-type":"co2-emission"}).text
        except:
            Co2 = "Nan"
        co2.append(Co2)

        try:
            Prev_owners = element.find('li', attrs={"data-type" : "previous-owners"}).text
        except:
            Prev_owners = "Nan"
        prev_owners.append(Prev_owners)
        try:
            Price = element.find('span', attrs={"class":"cldt-price sc-font-xl sc-font-bold"}).text
        except:
            Price = "Nan"
        price.append(Price)

        try:
            Hp = element.find('li', text =re.compile(r'CV')).text
        except:
            Hp = "Nan"
        hp.append(Hp)
        
        try:
            Location = element.find('span', attrs={"class":"cldf-summary-seller-contact-zip-city"}).text
        except:
            Location = "Nan"
        location.append(Location)

In [23]:
#Creating the Coupe_Cars_DataFrame
coupe_cars_df = pd.DataFrame({"Title":title,
                        "Version":version,
                        "Year": year,
                        "Kms": kms,
                        "Hp": hp,
                        "Fuel_type": fuel,
                        "Gear_type": gear,
                        "Fuel_l/100km": fuel_cons,
                        "CO2_g/Km": co2,
                        "Previous_owners": prev_owners,
                        "City_ZIP" : location,
                        "Price_EUR": price,
                        "Category" : "Coupe",
                        "Doors" : "3"})

In [24]:
coupe_cars_df

,Title,Version,Year,Kms,Hp,Fuel_type,Gear_type,Fuel_l/100km,CO2_g/Km,Previous_owners,City_ZIP,Price_EUR,Category,Doors
0,Mercedes-Benz C 200,Sportcoup√© K,\n09/2003\n,\n267.000 km\n,\n120 kW (163 CV)\n,\nGasolina\n,\nAutom√°tico\n,"\n9,7 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,8304 MATARO,"\n‚Ç¨ 2.950,-\n",Coupe,3
1,Mercedes-Benz C 200,C 200 Sportcoup√© K,\n01/2002\n,\n203.000 km\n,\n120 kW (163 CV)\n,\nGasolina\n,\nManual\n,"\n9,7 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,29004 MALAGA,"\n‚Ç¨ 2.950,-\n",Coupe,3
2,BMW 320,Ci,\n06/2002\n,\n186.600 km\n,\n125 kW (170 CV)\n,\nGasolina\n,\nManual\n,"\n8,9 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,46980 PATERNA,"\n‚Ç¨ 4.600,-\n",Coupe,3
3,Mercedes-Benz CLK 200,K,\n03/2004\n,\n291.200 km\n,\n120 kW (163 CV)\n,\nGasolina\n,\nManual\n,"\n12,2 l/100 km (mixto)\nPuede obtenerse infor...",\n- (g/km)\n,\n- (Propietarios)\n,46980 PATERNA,"\n‚Ç¨ 4.700,-\n",Coupe,3
4,Audi Coupe,2.0 20V 157 CV,\n11/1989\n,\n146.000 km\n,\n110 kW (150 CV)\n,\nGasolina\n,\nManual\n,"\n6,7 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,46930 QUART DE POBLET,"\n‚Ç¨ 5.490,-\n",Coupe,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,Jaguar XK,XK8 Coup√© 4.2 Final Edition Aut.,\n06/2006\n,\n73.000 km\n,\n221 kW (300 CV)\n,\nGasolina\n,\nAutom√°tico\n,"\n11,3 l/100 km (mixto)\nPuede obtenerse infor...",\n- (g/km)\n,\n- (Propietarios)\n,48450 ETXEBARRI,"\n‚Ç¨ 22.500,-\n",Coupe,3
396,BMW 218,dA Coup√©,\n04/2017\n,\n53.589 km\n,\n110 kW (150 CV)\n,\nDi√©sel\n,\nAutom√°tico\n,"\n3,8 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,28050 MADRID,"\n‚Ç¨ 22.754,-\n",Coupe,3
397,Mercedes-Benz 420,SL SL,\n06/1985\n,\n128.000 km\n,\n160 kW (218 CV)\n,\nOtros\n,\nAutom√°tico\n,\n0 l/100 km (mixto)\nPuede obtenerse informac...,\n- (g/km)\n,\n- (Propietarios)\n,08020 BARCELONA,"\n‚Ç¨ 22.890,-\n",Coupe,3
398,BMW 420,420dA Gran Coup√©,\n04/2017\n,\n129.000 km\n,\n140 kW (190 CV)\n,\nDi√©sel\n,\nAutom√°tico\n,\n4 l/100 km (mixto)\nPuede obtenerse informac...,\n- (g/km)\n,\n- (Propietarios)\n,37184 VILLARES DE LA REINA,"\n‚Ç¨ 22.900,-\n",Coupe,3
399,Mercedes-Benz E 220,BlueTec Coup√©,\n04/2016\n,\n119.000 km\n,\n125 kW (170 CV)\n,\nDi√©sel\n,\nManual\n,"\n4,6 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,28970 HUMANES DE MADRID,"\n‚Ç¨ 22.990,-\nIVA deducible\n",Coupe,3

In [25]:
#Defining columns for cabrio cars
title = []
version = []
year = []
kms = []
hp = []
gear = []
fuel = []
fuel_cons = []
co2 =[]
prev_owners = []
price = []
location = []

In [26]:
#Scapping cabrio cars

for cabrio_cars_page in all_pages:
    
    cabrio_cars_page = requests.get("https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=" + str(cabrio_cars_page) + "&cy=E&body=2&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&")
    cabrio_cars_soup = BeautifulSoup(cabrio_cars_page.text,"lxml")
    cabrio_cars_ads = cabrio_cars_soup.find_all('div', attrs={"class": "cl-list-element cl-list-element-gap"})
    
    sleep(randint(2,10))
    
    for element in cabrio_cars_ads:
        try:
            Title = element.find('h2', attrs={"class":'cldt-summary-makemodel sc-font-bold sc-ellipsis'}).text
        except:
            Title = "Nan"
        title.append(Title)
        
        try:
            Version = element.find('h2', attrs={"class":"cldt-summary-version sc-ellipsis"}).text
        except:
            Version = "Nan"
        version.append(Version)
        try:
            Year = element.find('li', attrs={'data-type':'first-registration'}).text
        except:
            Year = "Nan"
        year.append(Year)
        try:
            Kms = element.find('li', attrs={"data-type" : "mileage"}).text
        except:
            Kms = "Nan"
        kms.append(Kms)

        try:
            Gear = element.find('li', attrs={"data-type":"transmission-type"}).text
        except:
            Gear = "Nan"
        gear.append(Gear)

        try:
            Fuel = element.find('li', attrs={"class":"summary_item_no_bottom_line"}).text
        except:
            Fuel = "Nan"
        fuel.append(Fuel)

        try:
            Fuel_cons = element.find('li', attrs={"data-type":"combined-consumption"}).text
        except:
            Fuel_cons = "Nan"
        fuel_cons.append(Fuel_cons)

        try:
            Co2 = element.find('li', attrs={"data-type":"co2-emission"}).text
        except:
            Co2 = "Nan"
        co2.append(Co2)

        try:
            Prev_owners = element.find('li', attrs={"data-type" : "previous-owners"}).text
        except:
            Prev_owners = "Nan"
        prev_owners.append(Prev_owners)
        try:
            Price = element.find('span', attrs={"class":"cldt-price sc-font-xl sc-font-bold"}).text
        except:
            Price = "Nan"
        price.append(Price)

        try:
            Hp = element.find('li', text =re.compile(r'CV')).text
        except:
            Hp = "Nan"
        hp.append(Hp)
        
        try:
            Location = element.find('span', attrs={"class":"cldf-summary-seller-contact-zip-city"}).text
        except:
            Location = "Nan"
        location.append(Location)

In [27]:
#Creating the Cabrio_Cars_DataFrame
cabrio_cars_df = pd.DataFrame({"Title":title,
                        "Version":version,
                        "Year": year,
                        "Kms": kms,
                        "Hp": hp,
                        "Fuel_type": fuel,
                        "Gear_type": gear,
                        "Fuel_l/100km": fuel_cons,
                        "CO2_g/Km": co2,
                        "Previous_owners": prev_owners,
                        "City_ZIP" : location,
                        "Price_EUR": price,
                        "Category" : "Cabrio",
                        "Doors" : "3"})

In [28]:
cabrio_cars_df

,Title,Version,Year,Kms,Hp,Fuel_type,Gear_type,Fuel_l/100km,CO2_g/Km,Previous_owners,City_ZIP,Price_EUR,Category,Doors
0,Mitsubishi Colt,CZC 1.5 16v Instyle,\n06/2006\n,\n83.000 km\n,\n80 kW (109 CV)\n,\nGasolina\n,\nManual\n,"\n6,6 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,46930 QUART DE POBLET,"\n‚Ç¨ 2.200,-\n",Cabrio,3
1,Peugeot 206,CC 1.6 110,\n09/2005\n,\n197.700 km\n,\n81 kW (110 CV)\n,\nDi√©sel\n,\nManual\n,\n- (l/100 km)\n,\n- (g/km)\n,\n- (Propietarios)\n,30161 Llano de Brujas,"\n‚Ç¨ 2.700,-\n",Cabrio,3
2,Opel Astra,Twin Top 1.6 Enjoy,\n10/2007\n,\n110.000 km\n,\n77 kW (105 CV)\n,\nGasolina\n,\nManual\n,\n7 l/100 km (mixto)\nPuede obtenerse informac...,\n- (g/km)\n,\n- (Propietarios)\n,23700 LINARES,"\n‚Ç¨ 3.999,-\n",Cabrio,3
3,Renault Megane,C.C. 1.9DCI Luxe Dynamique 130,\n07/2005\n,\n200.000 km\n,\n96 kW (131 CV)\n,\nDi√©sel\n,\nManual\n,"\n5,8 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,24009 LEON,"\n‚Ç¨ 5.000,-\n",Cabrio,3
4,Volkswagen Beetle,Cabrio 1.9TDI,\n04/2004\n,\n177.300 km\n,\n73 kW (99 CV)\n,\nDi√©sel\n,\nManual\n,"\n5,5 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,48960 GALDAKAO,"\n‚Ç¨ 5.490,-\n",Cabrio,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,MG TF,1.6 115 Sky Blue,\n04/2004\n,\n83.800 km\n,\n84 kW (114 CV)\n,\nGasolina\n,\nManual\n,\n7 l/100 km (mixto)\nPuede obtenerse informac...,\n- (g/km)\n,\n- (Propietarios)\n,Nan,"\n‚Ç¨ 5.250,-\n",Cabrio,3
396,MG TF,1.6 115 Sky Blue,\n04/2004\n,\n83.800 km\n,\n84 kW (114 CV)\n,\nGasolina\n,\nManual\n,\n7 l/100 km (mixto)\nPuede obtenerse informac...,\n- (g/km)\n,\n- (Propietarios)\n,Nan,"\n‚Ç¨ 5.250,-\n",Cabrio,3
397,Peugeot 207,CC 1.6HDI FAP Sport 110,\n06/2007\n,\n132.000 km\n,\n80 kW (109 CV)\n,\nDi√©sel\n,\nManual\n,"\n5,2 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,29601 MARBELLA,"\n‚Ç¨ 5.299,-\nIVA deducible\n",Cabrio,3
398,BMW 318,Serie 3 E46/2 Cabrio Aut. Cabrio,\n08/2004\n,\n197.000 km\n,\n105 kW (143 CV)\n,\nGasolina\n,\nAutom√°tico\n,"\n8,1 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,Nan,"\n‚Ç¨ 5.299,-\nIVA deducible\n",Cabrio,3
399,smart forTwo,Cabrio 52 mhd Passion Aut.,\n08/2009\n,\n48.000 km\n,\n52 kW (71 CV)\n,\nGasolina\n,\nSemiautom√°tico\n,"\n4,5 l/100 km (mixto)\nPuede obtenerse inform...",\n105 g/km (mixto)\nPuede obtenerse informaci√≥...,\n- (Propietarios)\n,Nan,"\n‚Ç¨ 5.350,-\n",Cabrio,3

In [29]:
#Defining columns for suv cars
title = []
version = []
year = []
kms = []
hp = []
gear = []
fuel = []
fuel_cons = []
co2 =[]
prev_owners = []
price = []
location = []

In [30]:
#Scapping suv cars

for suv_cars_page in all_pages:
    
    suv_cars_page = requests.get("https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=" + str(suv_cars_page) + "&cy=E&body=4&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&")
    suv_cars_soup = BeautifulSoup(suv_cars_page.text,"lxml")
    suv_cars_ads = suv_cars_soup.find_all('div', attrs={"class": "cl-list-element cl-list-element-gap"})
    
    sleep(randint(2,10))
    
    for element in suv_cars_ads:
        try:
            Title = element.find('h2', attrs={"class":'cldt-summary-makemodel sc-font-bold sc-ellipsis'}).text
        except:
            Title = "Nan"
        title.append(Title)
        
        try:
            Version = element.find('h2', attrs={"class":"cldt-summary-version sc-ellipsis"}).text
        except:
            Version = "Nan"
        version.append(Version)
        try:
            Year = element.find('li', attrs={'data-type':'first-registration'}).text
        except:
            Year = "Nan"
        year.append(Year)
        try:
            Kms = element.find('li', attrs={"data-type" : "mileage"}).text
        except:
            Kms = "Nan"
        kms.append(Kms)

        try:
            Gear = element.find('li', attrs={"data-type":"transmission-type"}).text
        except:
            Gear = "Nan"
        gear.append(Gear)

        try:
            Fuel = element.find('li', attrs={"class":"summary_item_no_bottom_line"}).text
        except:
            Fuel = "Nan"
        fuel.append(Fuel)

        try:
            Fuel_cons = element.find('li', attrs={"data-type":"combined-consumption"}).text
        except:
            Fuel_cons = "Nan"
        fuel_cons.append(Fuel_cons)

        try:
            Co2 = element.find('li', attrs={"data-type":"co2-emission"}).text
        except:
            Co2 = "Nan"
        co2.append(Co2)

        try:
            Prev_owners = element.find('li', attrs={"data-type" : "previous-owners"}).text
        except:
            Prev_owners = "Nan"
        prev_owners.append(Prev_owners)
        try:
            Price = element.find('span', attrs={"class":"cldt-price sc-font-xl sc-font-bold"}).text
        except:
            Price = "Nan"
        price.append(Price)

        try:
            Hp = element.find('li', text =re.compile(r'CV')).text
        except:
            Hp = "Nan"
        hp.append(Hp)
        
        try:
            Location = element.find('span', attrs={"class":"cldf-summary-seller-contact-zip-city"}).text
        except:
            Location = "Nan"
        location.append(Location)

In [31]:
#Creating the Suv_Cars_DataFrame
suv_cars_df = pd.DataFrame({"Title":title,
                        "Version":version,
                        "Year": year,
                        "Kms": kms,
                        "Hp": hp,
                        "Fuel_type": fuel,
                        "Gear_type": gear,
                        "Fuel_l/100km": fuel_cons,
                        "CO2_g/Km": co2,
                        "Previous_owners": prev_owners,
                        "City_ZIP" : location,
                        "Price_EUR": price,
                        "Category" : "Suv",
                        "Doors" : "5"})

In [32]:
suv_cars_df

,Title,Version,Year,Kms,Hp,Fuel_type,Gear_type,Fuel_l/100km,CO2_g/Km,Previous_owners,City_ZIP,Price_EUR,Category,Doors
0,Audi Allroad,2.7T quattro Tiptronic,\n07/2001\n,\n277.000 km\n,\n184 kW (250 CV)\n,\nGasolina\n,\nAutom√°tico\n,\n12 l/100 km (mixto)\nPuede obtenerse informa...,\n- (g/km)\n,\n- (Propietarios)\n,04230 VIATOR,"\n‚Ç¨ 2.650,-\n",Suv,5
1,Nissan X-Trail,2.5 Elegance,\n03/2004\n,\n108.900 km\n,\n121 kW (165 CV)\n,\nGasolina\n,\nManual\n,"\n9,6 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,18195 CULLAR VEGA,"\n‚Ç¨ 3.450,-\nIVA deducible\n",Suv,5
2,SsangYong REXTON,270 Full GRAN OCASION NACIONAL,\n12/2004\n,\n299.000 km\n,\n121 kW (165 CV)\n,\nDi√©sel\n,\nAutom√°tico\n,"\n8,6 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,23700 LINARES,"\n‚Ç¨ 3.499,-\n",Suv,5
3,Audi Allroad,2.5 TDI quattro Tiptronic,\n12/2003\n,\n389.000 km\n,\n132 kW (179 CV)\n,\nDi√©sel\n,\nAutom√°tico\n,"\n9,6 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,28891 VELILLA DE SAN ANTONIO,"\n‚Ç¨ 3.900,-\n",Suv,5
4,Kia Sorento,2.5CRDI EX2 TOD,\n10/2005\n,\n240.000 km\n,\n103 kW (140 CV)\n,\nDi√©sel\n,\nManual\n,"\n8,5 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,46910 BENETUSER,"\n‚Ç¨ 3.998,-\n",Suv,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,MINI Cooper Countryman,Cooper ALL4 Aut.,\n12/2018\n,\n55.000 km\n,\n100 kW (136 CV)\n,\nGasolina\n,\nAutom√°tico\n,\n6 l/100 km (mixto)\nPuede obtenerse informac...,\n- (g/km)\n,\n- (Propietarios)\n,29004 MALAGA,"\n‚Ç¨ 20.800,-\nIVA deducible\n",Suv,5
396,Mercedes-Benz GLA 200,GLA200dStyle,\n08/2017\n,\n87.700 km\n,\n100 kW (136 CV)\n,\nDi√©sel\n,\nManual\n,"\n4,2 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,41007 SEVILLA,"\n‚Ç¨ 20.840,-\n",Suv,5
397,Audi Q3,2.0TDI 110kW,\n11/2016\n,\n84.325 km\n,\n110 kW (150 CV)\n,\nDi√©sel\n,\nManual\n,"\n4,4 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,28050 MADRID,"\n‚Ç¨ 20.845,-\n",Suv,5
398,Peugeot 5008,GT 2.0L BlueHDi 133kW (180CV) S&S EAT8,\n07/2018\n,\n104.301 km\n,\n133 kW (181 CV)\n,\nDi√©sel\n,\nAutom√°tico\n,"\n4,9 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,28021 MADRID,"\n‚Ç¨ 20.890,-\n",Suv,5
399,BMW X3,xDrive 20d,\n07/2016\n,\n114.936 km\n,\n140 kW (190 CV)\n,\nDi√©sel\n,\nManual\n,"\n5,4 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,28021 MADRID,"\n‚Ç¨ 20.890,-\n",Suv,5

In [33]:
#Defining columns for Van cars
title = []
version = []
year = []
kms = []
hp = []
gear = []
fuel = []
fuel_cons = []
co2 =[]
prev_owners = []
price = []
location = []

In [34]:
#Scapping Van cars

for van_cars_page in all_pages:
    
    van_cars_page = requests.get("https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=" + str(van_cars_page) + "&cy=E&body=13&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&")
    van_cars_soup = BeautifulSoup(van_cars_page.text,"lxml")
    van_cars_ads = van_cars_soup.find_all('div', attrs={"class": "cl-list-element cl-list-element-gap"})
    
    sleep(randint(2,10))
    
    for element in van_cars_ads:
        try:
            Title = element.find('h2', attrs={"class":'cldt-summary-makemodel sc-font-bold sc-ellipsis'}).text
        except:
            Title = "Nan"
        title.append(Title)
        
        try:
            Version = element.find('h2', attrs={"class":"cldt-summary-version sc-ellipsis"}).text
        except:
            Version = "Nan"
        version.append(Version)
        try:
            Year = element.find('li', attrs={'data-type':'first-registration'}).text
        except:
            Year = "Nan"
        year.append(Year)
        try:
            Kms = element.find('li', attrs={"data-type" : "mileage"}).text
        except:
            Kms = "Nan"
        kms.append(Kms)

        try:
            Gear = element.find('li', attrs={"data-type":"transmission-type"}).text
        except:
            Gear = "Nan"
        gear.append(Gear)

        try:
            Fuel = element.find('li', attrs={"class":"summary_item_no_bottom_line"}).text
        except:
            Fuel = "Nan"
        fuel.append(Fuel)

        try:
            Fuel_cons = element.find('li', attrs={"data-type":"combined-consumption"}).text
        except:
            Fuel_cons = "Nan"
        fuel_cons.append(Fuel_cons)

        try:
            Co2 = element.find('li', attrs={"data-type":"co2-emission"}).text
        except:
            Co2 = "Nan"
        co2.append(Co2)

        try:
            Prev_owners = element.find('li', attrs={"data-type" : "previous-owners"}).text
        except:
            Prev_owners = "Nan"
        prev_owners.append(Prev_owners)
        try:
            Price = element.find('span', attrs={"class":"cldt-price sc-font-xl sc-font-bold"}).text
        except:
            Price = "Nan"
        price.append(Price)

        try:
            Hp = element.find('li', text =re.compile(r'CV')).text
        except:
            Hp = "Nan"
        hp.append(Hp)
        
        try:
            Location = element.find('span', attrs={"class":"cldf-summary-seller-contact-zip-city"}).text
        except:
            Location = "Nan"
        location.append(Location)

In [35]:
#Creating the Van_Cars_DataFrame
van_cars_df = pd.DataFrame({"Title":title,
                        "Version":version,
                        "Year": year,
                        "Kms": kms,
                        "Hp": hp,
                        "Fuel_type": fuel,
                        "Gear_type": gear,
                        "Fuel_l/100km": fuel_cons,
                        "CO2_g/Km": co2,
                        "Previous_owners": prev_owners,
                        "City_ZIP" : location,
                        "Price_EUR": price,
                        "Category" : "Furgoneta",
                        "Doors" : "3"})

In [36]:
van_cars_df

,Title,Version,Year,Kms,Hp,Fuel_type,Gear_type,Fuel_l/100km,CO2_g/Km,Previous_owners,City_ZIP,Price_EUR,Category,Doors
0,Citroen,BERLINGO 2.0 HDI LEADER,Nan,Nan,\n66 kW (90 CV)\n,\nDi√©sel\n,\nManual\n,Nan,\n- (g/km)\n,Nan,02006 ALBACETE,"\n‚Ç¨ 1.990,-\n",Furgoneta,3
1,Fiat,Fiorino 1.3MJET FURGON,Nan,Nan,\n55 kW (75 CV)\n,\nDi√©sel\n,\nManual\n,Nan,\n- (g/km)\n,Nan,08921 BADALONA,"\n‚Ç¨ 2.980,-\n",Furgoneta,3
2,Renault,Kangoo 1.9DCI Authentique 4x4,Nan,Nan,\n62 kW (84 CV)\n,\nDi√©sel\n,\nManual\n,Nan,\n- (g/km)\n,Nan,23400 UBEDA,"\n‚Ç¨ 3.000,-\n",Furgoneta,3
3,Renault,Kangoo 1.9D Gran Volumen 65,Nan,Nan,\n47 kW (64 CV)\n,\nDi√©sel\n,\nManual\n,Nan,\n- (g/km)\n,Nan,48270 MARKINA,"\n‚Ç¨ 3.100,-\n",Furgoneta,3
4,Fiat,Dobl√≥ Combi 1.3Mjt Actual,Nan,Nan,\n55 kW (75 CV)\n,\nDi√©sel\n,\nManual\n,Nan,\n- (g/km)\n,Nan,28359 TITULCIA,"\n‚Ç¨ 3.500,-\n",Furgoneta,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,Peugeot,Partner Tepee 1.6HDI Confort 75,Nan,Nan,\n55 kW (75 CV)\n,\nDi√©sel\n,\nManual\n,Nan,\n- (g/km)\n,Nan,8241 Manresa,"\n‚Ç¨ 3.900,-\n",Furgoneta,3
396,Peugeot,Partner Tepee 1.6HDI Confort 75,Nan,Nan,\n55 kW (75 CV)\n,\nDi√©sel\n,\nManual\n,Nan,\n- (g/km)\n,Nan,48960 GALDAKANO,"\n‚Ç¨ 3.900,-\n",Furgoneta,3
397,Peugeot,Partner Tepee 1.6HDI Confort 75,Nan,Nan,\n55 kW (75 CV)\n,\nDi√©sel\n,\nManual\n,Nan,\n- (g/km)\n,Nan,28850 TORREJON DE ARDOZ,"\n‚Ç¨ 3.900,-\n",Furgoneta,3
398,Peugeot,Partner Tepee 1.6HDI Confort 75,Nan,Nan,\n55 kW (75 CV)\n,\nDi√©sel\n,\nManual\n,Nan,\n- (g/km)\n,Nan,41007 SEVILLA,"\n‚Ç¨ 3.900,-\n",Furgoneta,3
399,Renault Twingo,Societ√© 1.5 dCi 75 Fase2,\n07/2013\n,\n127.000 km\n,\n55 kW (75 CV)\n,\nDi√©sel\n,\nManual\n,"\n3,6 l/100 km (mixto)\nPuede obtenerse inform...",\n90 g/km (mixto)\nPuede obtenerse informaci√≥n...,\n- (Propietarios)\n,Nan,"\n‚Ç¨ 3.900,-\nIVA deducible\n",Furgoneta,3

In [37]:
#Defining columns for Other cars
title = []
version = []
year = []
kms = []
hp = []
gear = []
fuel = []
fuel_cons = []
co2 =[]
prev_owners = []
price = []
location = []

In [38]:
#Scapping Other cars

for other_cars_page in all_pages:
    
    other_cars_page = requests.get("https://www.autoscout24.es/lst/?sort=standard&desc=0&offer=D%2CJ%2CO%2CU&ustate=N%2CU&size=20&page=" + str(other_cars_page) + "&cy=E&body=7&atype=C&recommended_sorting_based_id=add4f573-8a91-417b-8217-546c0129def6&")
    other_cars_soup = BeautifulSoup(other_cars_page.text,"lxml")
    other_cars_ads = other_cars_soup.find_all('div', attrs={"class": "cl-list-element cl-list-element-gap"})
    
    sleep(randint(2,10))
    
    for element in other_cars_ads:
        try:
            Title = element.find('h2', attrs={"class":'cldt-summary-makemodel sc-font-bold sc-ellipsis'}).text
        except:
            Title = "Nan"
        title.append(Title)
        
        try:
            Version = element.find('h2', attrs={"class":"cldt-summary-version sc-ellipsis"}).text
        except:
            Version = "Nan"
        version.append(Version)
        try:
            Year = element.find('li', attrs={'data-type':'first-registration'}).text
        except:
            Year = "Nan"
        year.append(Year)
        try:
            Kms = element.find('li', attrs={"data-type" : "mileage"}).text
        except:
            Kms = "Nan"
        kms.append(Kms)

        try:
            Gear = element.find('li', attrs={"data-type":"transmission-type"}).text
        except:
            Gear = "Nan"
        gear.append(Gear)

        try:
            Fuel = element.find('li', attrs={"class":"summary_item_no_bottom_line"}).text
        except:
            Fuel = "Nan"
        fuel.append(Fuel)

        try:
            Fuel_cons = element.find('li', attrs={"data-type":"combined-consumption"}).text
        except:
            Fuel_cons = "Nan"
        fuel_cons.append(Fuel_cons)

        try:
            Co2 = element.find('li', attrs={"data-type":"co2-emission"}).text
        except:
            Co2 = "Nan"
        co2.append(Co2)

        try:
            Prev_owners = element.find('li', attrs={"data-type" : "previous-owners"}).text
        except:
            Prev_owners = "Nan"
        prev_owners.append(Prev_owners)
        try:
            Price = element.find('span', attrs={"class":"cldt-price sc-font-xl sc-font-bold"}).text
        except:
            Price = "Nan"
        price.append(Price)

        try:
            Hp = element.find('li', text =re.compile(r'CV')).text
        except:
            Hp = "Nan"
        hp.append(Hp)
        
        try:
            Location = element.find('span', attrs={"class":"cldf-summary-seller-contact-zip-city"}).text
        except:
            Location = "Nan"
        location.append(Location)

In [39]:
#Creating the Other_Cars_DataFrame
other_cars_df = pd.DataFrame({"Title":title,
                        "Version":version,
                        "Year": year,
                        "Kms": kms,
                        "Hp": hp,
                        "Fuel_type": fuel,
                        "Gear_type": gear,
                        "Fuel_l/100km": fuel_cons,
                        "CO2_g/Km": co2,
                        "Previous_owners": prev_owners,
                        "City_ZIP" : location,
                        "Price_EUR": price,
                        "Category" : "Furgoneta",
                        "Doors" : "Nan"})

In [40]:
#Mergin all DataFrames 
all_cars_df = pd.concat([small_cars_df,
                         sedan_cars_df,
                         familiar_cars_df,
                         minivan_cars_df,
                         coupe_cars_df,
                         cabrio_cars_df,
                         suv_cars_df,
                         van_cars_df,
                         other_cars_df], axis = 0)
#Reset_index
all_cars_df = all_cars_df.reset_index()

In [41]:
all_cars_df.drop(["index"],axis = 1)

,Title,Version,Year,Kms,Hp,Fuel_type,Gear_type,Fuel_l/100km,CO2_g/Km,Previous_owners,City_ZIP,Price_EUR,Category,Doors
0,SEAT Cordoba,1.9 TDi Sport 90,\n12/2000\n,\n254.000 km\n,\n66 kW (90 CV)\n,\nDi√©sel\n,\nManual\n,"\n4,9 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,18195 CULLAR VEGA,"\n‚Ç¨ 980,-\nIVA deducible\n",Peque√±o,5
1,Renault Megane,1.6 Century,\n08/2001\n,\n190.000 km\n,\n82 kW (111 CV)\n,\nGasolina\n,\nManual\n,\n7 l/100 km (mixto)\nPuede obtenerse informac...,\n- (g/km)\n,\n- (Propietarios)\n,28891 VELILLA DE SAN ANTONIO,"\n‚Ç¨ 1.500,-\n",Peque√±o,5
2,Daewoo Lanos,1.6 16v. SX,\n06/2000\n,\n185.000 km\n,\n78 kW (106 CV)\n,\nGasolina\n,\nManual\n,"\n8,2 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,46940 MANISES,"\n‚Ç¨ 1.500,-\n",Peque√±o,5
3,SEAT Ibiza,1.4 Stella,\n11/2001\n,\n167.577 km\n,\n44 kW (60 CV)\n,\nGasolina\n,\nManual\n,"\n6,6 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,08310 ARGENTONA,"\n‚Ç¨ 1.600,-\n",Peque√±o,5
4,Alfa Romeo 145,1.6 TS Lujo 16v,\n04/1997\n,\n127.000 km\n,\n88 kW (120 CV)\n,\nGasolina\n,\nManual\n,"\n7,8 l/100 km (mixto)\nPuede obtenerse inform...",\n- (g/km)\n,\n- (Propietarios)\n,46940 MANISES,"\n‚Ç¨ 1.850,-\n",Peque√±o,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,Ford Puma,ST-LINE 1.0 EcoBoost MHEV 92KW (125CV) Euro 6.2,\n11/2020\n,\n12.991 km\n,\n92 kW (125 CV)\n,\nOtros\n,\nManual\n,\n- (l/100 km)\n,\n- (g/km)\n,\n- (Propietarios)\n,48940 LEIOA,"\n‚Ç¨ 17.900,-\n",Furgoneta,Nan
3596,Renault,TRAFIC 1.6 DCI COMBI 9,Nan,Nan,\n70 kW (95 CV)\n,\nDi√©sel\n,\nManual\n,Nan,\n- (g/km)\n,Nan,14014 CORDOBA,"\n‚Ç¨ 17.900,-\n",Furgoneta,Nan
3597,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Nan,Furgoneta,Nan
3598,Mercedes-Benz S 280,(),\n09/1972\n,\n98.000 km\n,\n- kW (- CV)\n,\nGasolina\n,\nManual\n,\n- (l/100 km)\n,\n- (g/km)\n,\n- (Propietarios)\n,3007 Alicante,"\n‚Ç¨ 17.950,-\n",Furgoneta,Nan
3599,BMW i3,94 Ah,\n11/2017\n,\n40.100 km\n,\n125 kW (170 CV)\n,\nEl√©ctrico\n,\n- (Cambio)\n,\n- (l/100 km)\n,\n0 g/km (mixto)\nPuede obtenerse informaci√≥n ...,\n- (Propietarios)\n,Nan,"\n‚Ç¨ 17.990,-\n",Furgoneta,Nan

In [42]:
all_cars_df.to_csv('cars.csv', header=True, index=False)